### ISSUE TITLE
After moving a selection, raster is burned from edge to edge[Bug]: 

### ISSUE THREAD

**Issue by bergie5737** [meerk40t/meerk40t#1008]
### Summary Description

I have a very small file with two heart shapes and text  to raster. The operation completes successfully when opening the file the first time. After moving the selection to a new position, to start a new cut, a large portion of the raster operation simply burns from edge to edge, there are no spaces between the letters. It is as if everything is filled with black. After I reset the laser or at least disconnect the USB and reconnect, the new position is cut correctly. It fails again when moving to a new area.

![Laser ignore](https://user-images.githubusercontent.com/10572409/165011498-8cff99a0-d926-4106-a427-439cc596ee35.jpg)

The bottom image is what it should look like. Top left is a typical failure. The raster starts from the bottom up in these images. As can be seen from the first image, It fixed itself later on. Top right started to fail and I reset the laser as described and it completed the raster as expected in the exact same position. (The extra engraving in the filled in area is where it engraved the second time.) This gives me the impression that the issue is with Meerk40t and not my laptop. 

### Crash logs

```shell
None. Operation simply fail to recognize the "gaps" between the outlines after moving the selection.
```

### MeerK40t Version

7.5 beta1 and 7.6.0

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by tatarize** [comment]
Can you provide the file you're using to do this? I don't quite grasp the steps to repeat the problem. You load it up and run it and it's fine, but if you move it, then it's suddenly a manifest failure?
