### ISSUE TITLE
[Minor bug] Recent file list doesn't display "&" in file names

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1081]
If you open / import a file which has an ampersand in the filename, then when it is listed in `Recent files` the ampersand is converted into a shortcut key with an underscore on the following character.

The filename needs ampersands to be escaped when it is added to this list.

**Comment by tatarize** [comment]
Fixed in c4bb30e5d389bbc6c189b5882cf1521ed3c22681
