### ISSUE TITLE
Problem when importing DXF or DWG files[Bug]: 

### ISSUE THREAD

**Issue by LeonardoCT** [meerk40t/meerk40t#1187]
### Summary Description

DXF files not importing correctly. 

### Additional Details

When i try to import dxf or dwg files the round edges become straight:

[2D cad software]:
![Immagine 2022-07-22 141507](https://user-images.githubusercontent.com/20495117/180437244-79be7c28-a83d-4c99-85c3-0861fe42f9bc.png)
[meerk40T]:
![Immagine 2022-07-22 141629](https://user-images.githubusercontent.com/20495117/180437367-250249ee-1ae1-432e-927a-bd3012a62a4d.png)
[K40 whisperer]:
![image](https://user-images.githubusercontent.com/20495117/180437445-9bd2175b-6871-4183-858b-a63f81d81a4f.png)
As you can see, the 2D drawing is fine, when i import it in K40 whisperer it works fine, but when i try to use Meerk40T the round edges become straight, and i have no idea how to fix this, as it seems like an import issue.
Thanks

### Crash logs

```shell
Nothing to put here
```

### MeerK40t Version

V0.7.7001

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by tatarize** [comment]
I might need an example of that file. Basically dxf has a *lot* of different bits that can be messed up and figuring out what's wrong requires an example file. The smaller the better. Removing as much as you can that isn't relevant to the failure is certainly helpful.

**Comment by LeonardoCT** [comment]
[Koala.dxf.zip](https://github.com/meerk40t/meerk40t/files/9184181/Koala.dxf.zip)
Here is the file, however i found a very simple work around,
i switched to svg files and it works perfectly

**Comment by tatarize** [comment]
![image](https://user-images.githubusercontent.com/3302478/189515877-cc342ec9-54e2-4640-9cb9-48894a43cc71.png)
