### ISSUE TITLE
CH341 EEPROM Dumps

### ISSUE THREAD

**Issue by joerlane** [meerk40t/meerk40t#123]
Pulled using https://github.com/stefanct/ch341eepromtool

[ch341.zip](https://github.com/meerk40t/meerk40t/files/4088488/ch341.zip)

**Comment by tatarize** [comment]
Yeah, solid try, but I guess the chip doesn't have anything of use in there.
https://github.com/meerk40t/meerk40t/wiki/K40's-CH431A-EEPROM-dump

**Comment by tatarize** [comment]
[dump.just_binary_fake.zip](https://github.com/meerk40t/meerk40t/files/4090493/dump.just_binary_fake.zip)

**Comment by joerlane** [comment]
![Screen Shot 2020-01-21 at 2 44 13 PM](https://user-images.githubusercontent.com/3026093/72841655-ca7ff100-3c64-11ea-8a75-5ec0777e0f20.png)

**Comment by joerlane** [comment]
![Screen Shot 2020-01-21 at 11 46 49 PM](https://user-images.githubusercontent.com/3026093/72866357-ffae3280-3ca8-11ea-8b39-34cfa8ef150f.png)

**Comment by joerlane** [comment]
[CH341DLL.H.zip](https://github.com/meerk40t/meerk40t/files/4095410/CH341DLL.H.zip)
