### ISSUE TITLE
[Bug]: Error when submitting work to laser engraver.

### ISSUE THREAD

**Issue by RossMich1** [meerk40t/meerk40t#1279]
### Summary Description

Hi There,

When I execute the work for engraving I get this error:

![Capture](https://user-images.githubusercontent.com/111974404/186403505-ff725daa-6bb2-4447-b6e4-662316ec2c1f.PNG)

I'm trying to engrave this onto a piece of cardboard:

![Capture2](https://user-images.githubusercontent.com/111974404/186403678-93e923c5-0d68-44e7-a5b6-aad3c547cdaa.PNG)

I've followed this [YouTuber ](https://www.youtube.com/watch?v=ynTFqAd5HR0&ab_channel=UKRocketry)and I've followed his steps exactly and keep getting the same error. I'm still new to this and this is probably me being inexperienced with laser cutters but would appreciate some help.

### Additional Details

Laser cutter K40 with Moshi Board.

### MeerK40t Version

v0.8.00.19

### MeerK40t Type

Source (zip/tar file from Github)

### Your Operating System

Windows

**Comment by tatarize** [comment]
It's probably a crash bug. It's very close to done, but I've not broken out my moshiboard for that kind of testing yet so it probably went unseen.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.8.0020

Here pushed a new version. Should have files soon. Includes several small Moshi fixes that prevented it from working. If there's any more trouble you should probably switch to the stable version of 0.7.7
