### ISSUE TITLE
[Request] Tree context menu for element nodes to Unclassify emphasised nodes

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1351]
Rather than go to the (multiple) Ops and find and remove element references from non-hierarchical lists, it would be easier to select element nodes and right-click to unclassify and remove from operations.

P.S. Useful in 0.7 but more useful in 0.8 where hierarchy is retained on save.

**Comment by jpirnay** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/2670784/192649734-e3c71da5-8105-4f0c-8212-a6af08bf8b32.png">

**Comment by Sophist-UK** [comment]
I hadn't spotted that (perhaps because it is new)!! 😃

The language is inconsistent and IMO a little confusing (despite me being relatively knowledgeable about MK). In preferences we talk about classification, here we talk about assignment and references. And even I am unsure what "Inherit" means in this context?

I am not personally wedded (not that this matters since I am no longer a developer and was never Tat) to "Classify" / "Classification"; "Assign" / "Assignment" is equally good, or perhaps "Classification" is the name of automated "Assignment". It might be better to drop one and replace "Classification" with "Automated assignment".

So in preferences, it might be better to replace "Classify" with "Assign" in labels and tooltips, add a tooltip to the tab itself.

In the tree context menu I definitely think that "Remove all references from all ops" should be "Unassign from all ops".

And my guess about "Inherit stroke and classify similar" is that it means "Assign automatically based on Stroke colour"; and ditto for fill. Perhaps this description would be more consistent terminology. 😄

**Also,** the assignment menu needs to be added to groups, files and the Elements node.

**Comment by jpirnay** [comment]
> Also, the assignment menu needs to be added to groups, files and the Elements node.
Added files and groups. Overlooked the elements idea

**Comment by jpirnay** [comment]
My (personal) definition:
Classfication is the (automatic) process of assigning an element to an operation. That link between element and operation is called an assignment.

**Comment by Sophist-UK** [comment]
Yes - that is my definition also, but if you use "Classification" to mean "Automatic assignment", then you need to explain this in a tooltip or text label so that everyone else can understand it too, and it may simply be easier to use "Automated assignment".

That said, there are also tree context menu items (on the Operations node) which talk about reclassifying, so there are probably more places than just Preferences where this is used.

**Comment by jpirnay** [comment]
I will look into the different uses of the terms
