### ISSUE TITLE
Simulation Suggestions: Frame Per Second, Playback Clock

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#1424]
* [x] Simulation playback at 5000% is still painfully slow. 
* [x] **Feature request:** I really think that playback "frames per second" needs to be variable depending on burn time i.e. so that playback is nearer real-time. 
* [x] **Feature request:** A playback clock showing elapsed time vs. total or remaining time would also be nice (as a future enhancement).

**Comment by jpirnay** [comment]
A new timed view in the simulation panel will provide these functionalities
