### ISSUE TITLE
DPI Labeling, Bugs

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#1427]
* [x] Raster operation node label would benefit from DPI being shown - in 0.7 the step value was shown.
* [x] Changing DPI on images is screwed up - multiple issues I think including: labels not changing when using Raster Wizard or DPI right click or changing on OP and not ELEMENT nodes or vice versa, right click to set Raster Wizard or DPI on multiple selected images not working etc.
* [x] Image dithering is now disabled by default and doesn't get turned on when you use the Raster Wizard or set DPI.

**Comment by jpirnay** [comment]
"Set dpi" may still be a misconception of the purpose of dpi --> see [Issue #1394](https://github.com/meerk40t/meerk40t/issues/1394)
