### ISSUE TITLE
[0.8.1] Group node labels - no of children

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1443]
Any chance that the Group element node labels can have:
1. A space between the inkscape name and the "(" i.e. `name (2 elements)` rather than `name(2 elements)`?
2. Show not only the count of direct child elements but also a count of all descendent elements i.e. `(2 children, 20 total)`?

**Comment by jpirnay** [comment]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/2670784/198542893-cb533297-6240-4bf8-a058-108d05663272.png">
Will be part of the next release
