### ISSUE TITLE
[0.8.1] Spooler - Queue estimate is twice actual estimate

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1448]
This screen shot shows the exact same job queued twice. As you can see the second job has twice the estimated time of the first job...
![image](https://user-images.githubusercontent.com/3001893/198683617-5ac297dd-c8af-4101-9a9c-3e2c07cedecb.png)

**Comment by jpirnay** [comment]
The estimate is updated during execution and takes the amount of things done and the remaining tasks into account

**Comment by Sophist-UK** [comment]
No - they should both say 11:07 as an estimated time - the Estimate for a burn job doesn't change until the item run time reaches the item estimate, and then the item estimate increases in step with the item run time and the total estimate increases with that.

This is a bug.

**Comment by jpirnay** [comment]
Fixed

**Comment by Sophist-UK** [comment]
So - it was a bug then?

**Comment by jpirnay** [comment]
It certainly was, thanks for reporting
