### ISSUE TITLE
[0.8.1] Spooler - Should run time keep increasing during interrupts?

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1456]
And if it should, then should the estimated time increase in step for the duration of the interrupt?

**Comment by jpirnay** [comment]
Good point

**Comment by jpirnay** [comment]
It's more complicated than anticipated, so no immediate resolution I am afraid, right now the runtime is calculated as the difference of current time vs starttime, which is independent of any window being open / watchdogs to look for interrupts etc.
A resolution would require a time keeping service.

**Comment by Sophist-UK** [comment]
1. What I would do to avoid a "time service" is to hold an adjusted start time - which is initially set to the actual start time, but which is adjusted when an `interrupt` special op is completed by adding the time take for the interrupt op. You could then use this to calculate the elapsed time.

2. If you are unable to adjust the elapsed time to exclude interrupt time, the alternative is to add the interrupt time onto the estimated time, and then use the actual start time to measure the elapsed time.

**Comment by tatarize** [comment]
Time the interrupts. Subtract that time from duration. *maybe*. You could want to know how long the job took including time you spent dealing with material etc.
