### ISSUE TITLE
[0.8.1] File New immediately followed by close asks to save

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1493]
![image](https://user-images.githubusercontent.com/3001893/201938322-f565644f-1648-488e-ab17-b38a0019bbfd.png)

**Comment by tatarize** [comment]
Accurate.

**Comment by tatarize** [comment]
New calls Validate_Save() but this gets overruled when the modifications to the nodes then calls `modified` as a signal saying something changed there. This probably got messed with after we fixed another issue where changing a operation value wouldn't trigger the save required dialog.
