### ISSUE TITLE
[0.8.1] Remove spooled job deletes everything

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1523]
I mistakenly pressed the Big Green "Go" button whilst my laser was burning, queuing a second version of the same job.

So I went into Spooler and selected the second job (queued) and right clicked and selected Remove JOb (or similar) and both jobs were removed and the laser immediately stopped. (Fortunately, I was able to run the job again and turn the laser on at the correct point, otherwise material would have been ruined.)

**Comment by jpirnay** [comment]
Fixed
