### ISSUE TITLE
[0.8.1] Raster time estimates still way off

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1525]
5 identical small images. This screen shot was 1/2 way through the second one.

![image](https://user-images.githubusercontent.com/3001893/204326414-0115e672-24f5-4234-9094-4abeaee92d3c.png)

Here is the history after it finished...
![image](https://user-images.githubusercontent.com/3001893/204327091-e934fb60-a99d-41be-9982-10140ba6b0f3.png)

**Comment by Sophist-UK** [comment]
Another example...
![image](https://user-images.githubusercontent.com/3001893/204328644-1e7a49e3-8577-4127-8255-c874a3cf0d4a.png)
![image](https://user-images.githubusercontent.com/3001893/204328722-9d003760-be91-406e-9f9b-723dbc378812.png)

**Comment by Sophist-UK** [comment]
Another example...
![image](https://user-images.githubusercontent.com/3001893/204346262-a45625e5-fe46-458a-af78-5286980eb285.png)
![image](https://user-images.githubusercontent.com/3001893/204347751-c42bd6ea-8102-4e30-8330-a6fb249d0d23.png)

**Comment by Sophist-UK** [comment]
Time estimates are `length / speed` for all element types, and it seems likely that `length` for rasters is a poor calculation at https://github.com/meerk40t/meerk40t/blob/master/meerk40t/core/cutcode/rastercut.py#L97-L102.

This calculation seems screwy. I suggest that the length calculation ignores overscan (because there are likely to be areas at the edges that are not rastered on some rows which will compensate), but (obviously) the length based on area in sq. mil needs to be divided by the step (whereas this seems to add some factor multiplied by the step). Also this seems to assume B2T or T2B raster so it will be wrong for L2R/R2L.

**Comment by jpirnay** [comment]
I agree, this looks dodgy - it's just calculcating pixels and not real distances, so the calculation fails. The calculation of the expected time in the operation property panel (which is using the intrinsic method of the operation for time estimates) is probably the way to go.
![grafik](https://user-images.githubusercontent.com/2670784/205456440-7903d95c-f680-4959-9244-236a0f630943.png)

![grafik](https://user-images.githubusercontent.com/2670784/205456379-1c787dad-7471-47ba-8448-baba076f9f23.png)

**Comment by jpirnay** [comment]
Not having a lot of spare time to code unfortunately, but I believe I have figured out why these estimates are so big...
<img width="566" alt="image" src="https://user-images.githubusercontent.com/2670784/206198663-294e12d7-87cf-4164-a8e3-2c8a8425ac91.png">

**Comment by Sophist-UK** [comment]
Here are two executions of the same raster, first at 450mm/s, second at 350mm/s (which should take longer)...
![image](https://user-images.githubusercontent.com/3001893/206201181-6d991d50-3da0-4579-9866-e0df739b5cc9.png)

**Comment by jpirnay** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/2670784/206207220-b0736dd7-5951-4c68-9c83-296432ce3ac8.png">
Hopefully that's fixed, too. Top-line 300 bottom line 450 mm/s
