### ISSUE TITLE
[0.8.1002] Right click execute of Image Op does tiny image in TL corner

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1526]

**Comment by jpirnay** [comment]
![grafik](https://user-images.githubusercontent.com/2670784/204505779-a1407eb9-b760-4187-9741-e794ed6fee9f.png)
Not sure how to recreate this?! Could you provide more details please?

**Comment by Sophist-UK** [comment]
I had a design with an image (DPI 500) and some vector engraves and cuts.

Normal burn worked fine. Normal burn with only Image op enabled worked fine. But repeated attempts (including reboot of K40 and reload of MK) to execute the Image op using right-click made the image very small in TL corner and it completed extremely quickly.

**Comment by Sophist-UK** [comment]
It may have been after I used the abort button. I will try to recreate it.

**Comment by Sophist-UK** [comment]
Yes - it appears to happen after an abort. Load this file. Click the BGB. Abort with the BRB. Home. Right-click and execute.
[TEMP](https://user-images.githubusercontent.com/3001893/204527910-4eb4487f-f2f6-4720-bc29-938a078d7913.svg)

**Comment by okto577buski** [comment]
Thanks for the useful information
