### ISSUE TITLE
[0.8.1] Crosshatch raster

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1528]
I just wanted to say thank you for the crosshatch image raster which I used for real today.

I was rastering a compass rose with very fine 1degree lines - and the vertical lines were faint whilst horizontal lines were bold.

So I did a cross-hatch raster and it came out great!!!

Am I right in thinking that this is an MK unique feature?

**Comment by tatarize** [comment]
I think it exists elsewhere. I'm pretty sure you can hatch in two directions. And I think the initial request cited prior art. #88
