### ISSUE TITLE
[0.8.2b2] Abort during 1st pass of cross-hatch raster works differently.

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1533]
Mostly does a home which doesn't happen during a non-crosshatch raster.

Cannot recreate, however.

**Comment by tatarize** [comment]
Abort should abort, regardless where it is. In cut planning the crosshatch rasters actually get turned into a horizontal and vertical raster of the same shape. So it shouldn't do anything different than a normal raster of whatever direction.

**Comment by Sophist-UK** [comment]
I think this is actually a change in how abort works because I have subsequently seen this behaviour (where it homes or even crashes into the left/top hard stops) during other operations - or indeed where it does a bunch of twitches after the proper burn stops..

I haven't had time to test whether a pause followed by an abort avoids this, but if so then the abort code might benefit from an implied pause first.
