### ISSUE TITLE
[0.8.1b2] PNG load incorrect cf. inkscape

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1535]
Inkscape: 
![image](https://user-images.githubusercontent.com/3001893/204591840-505fe6d0-1859-405d-8589-b17a9df5877e.png)

MK:
![image](https://user-images.githubusercontent.com/3001893/204592192-eed5d76b-6510-4329-b823-53f8bed403a4.png)

[File](https://user-images.githubusercontent.com/3001893/204592456-0a9cd9c0-1140-4881-a6bc-7190fb6d437a.svg)

**Comment by Sophist-UK** [comment]
Here is the same file loaded in 0.7.8:
![image](https://user-images.githubusercontent.com/3001893/204593082-5d716d4d-2a61-436a-a4ee-7af0b2494bb6.png)

**Comment by Sophist-UK** [comment]
Same file in 0.6.24:
![image](https://user-images.githubusercontent.com/3001893/204594086-6a87cdbf-4e0e-49c0-bfe7-1610c44e3ac5.png)

**Comment by Sophist-UK** [comment]
So I am going to have to go back to 0.6.24 to get it to burn correctly.

**Comment by jpirnay** [comment]
That's something for tatarize to look into, but from what I can gather the image viewbox is not adjusted properly?

**Comment by tatarize** [comment]
Either MK or svgelements isn't properly accounting for the `preserveAspectRatio="none"` being set. That should make it so the image width and height are the actual image width and height and the aspect ratio isn't preserved. But, it loaded up and make the image a solid square image anyway even though it was specifically told not to.

**Comment by tatarize** [comment]
This is corrected in commit: aea80f73ea4fc2c8ab126c00f9fa1bf386b747ba

The problem was I thought it was a good idea to call `"none"` as `None` when they mean completely different things. The first means there is no preservation of the aspect ratio. The latter means that the preservation isn't set therefore use the default which is `xMidyMid meet`.
