### ISSUE TITLE
[0.8.x] Possible suggestion: Image bounds are "cropped" when image is rotated

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1536]
Original:
![image](https://user-images.githubusercontent.com/3001893/204603288-89c9c616-8697-4860-a878-c4b59d256c07.png)
Rotate 90 degrees:
![image](https://user-images.githubusercontent.com/3001893/204603472-da497ac7-a561-4636-9688-ffe2eb44c6f7.png)
Rotate 45 degrees:
![image](https://user-images.githubusercontent.com/3001893/204603842-203d0d9b-578e-4359-a611-9caf0d2cc932.png)

The issue is that whilst the bounds of the original image fitted exactly within the bounds of a containing vector edge cut, the bounds of the new image no extend outside the bounds of the edge, and this can make the positioning of the whole item much more complicated. Of course, unless you actualise the image, the bounds are only a reflection of the transform matrix, so when you rotate it back again, the bounds return to the original size.

For the above example, where there is no transparent / white margin around the image, I would suggest that when the matrix rotation is not a multiple of 90 degrees, then the bounding box is calculated based on the non-transparent / non-white pixels. This would be calculated when the matrix is changed as an offset to the X/Y and W/H bounds values and held as attributes of the image object and used when the bounds are requested.

However an image could have transparent/white margins around the non-transparent/non-white pixels, (and for PNGs could have a mixture of white and transparent). For images like this you have two options:

a. As above, calculate the bounding box for the smallest non-transparent/non-white rectangle; or

b. Calculate the margins on all 4 sides of the original, rotate the image, calculate the minimal bounding box and then add the same margins back again. This feels too complicated though, and it would look odd esp. for 90 degree multiples because the margins wouldn't rotate with the image.

Neither of the above is perfect. A third alternative would be to:

c. Actually crop the image to non-transparent / non-white bounding box when it is loaded, and then calculate the equivalent cropped bounding box when you have a transformation. This would have the up side of consistency (both for images themselves, and how images behave cf. rotating vectors), and the downside that the image gets changed when it is loaded (though it would look the same).

**Comment by tatarize** [comment]
Obviously from the previous thing it's obvious that the rotation here is either wrong or weird. It's entirely the case that this lines up in Chrome but does not line up in MeerK40t so it's prima facie a bug, making this a bug bug.

**Comment by Sophist-UK** [comment]
It's not a bug bug IMO. It is a symptom of applying a transform to a rectangular boundary. However from a user perspective, it appears odd.

**Comment by jpirnay** [comment]
Some of it already works out of the box, apply a non harmful image operation like dither to the picture after rotation...
The image manipulation operations always crop the generated picture at the end.
I am working on it to make it consistent with scaling and rotation as well as making the crop feature selectable (it might not always be desired) - most of it works according to (my) expectations: https://github.com/meerk40t/meerk40t/pull/1555
