### ISSUE TITLE
[0.8.1] Spooler - Queued / executing jobs information 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1541]
There is a paucity of information in the Spooler queued / executing jobs information regarding the size of the job(s).
![image](https://user-images.githubusercontent.com/3001893/205498382-cf83b730-96fa-4f27-bf6e-0263f996db2a.png)
As you can see in the above example the currently executing job shows the size of the job as `(1191/1194)` where the units are unspecified but are presumably cut-objects, but the queued job doesn't show any such information.

It would be useful to separate out this information to individual columns and to have additional information shown i.e. number of operations executed, saved/loaded filename, max passes, etc.).

Such information would ideally be shown in the history too.

**Comment by tatarize** [comment]
This feels very open ended. The history stores a lot of history, and there's a lot of information to it. It's marked completed so I assume it is, but due to the open nature of the question it's not clear whether it actually was.
