### ISSUE TITLE
No Version Number Listed

### ISSUE THREAD

**Issue by kshenneman** [meerk40t/meerk40t#169]
Could you please include the version number in the About window.  After you download the software, there seems to be no way of telling what version you have, (Oh, I just found it...) except in the title bar of the application, which is very small and obscure.  Under the Meerkat logo on the About page would be a great location.

**Comment by tatarize** [comment]
Okay, added. My answer to minor aesthetic changes is basically always yes.

https://github.com/meerk40t/meerk40t/pull/160/commits/49631f5e67c33f451ad040a19e6184da39254ab7

Next versions about page looks like:

![aboutpage](https://user-images.githubusercontent.com/3302478/82485439-44e44480-9a90-11ea-8e9a-d131a6f172d9.png)

**Comment by tatarize** [comment]
This issue was corrected in 0.6.0. Which is now in full release.
