### ISSUE TITLE
Reload file does not reload changes but complete file

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#176]
If I make some external changes to a file and click "reload file" I expect that the current loaded file in Meerk40t is updated to reflect the changes. 
It does update the changes, but merely by reloading *all* elements. By doing so, you end up with all the elements, the old ones as well as the new ones (and all unchanged element are loaded twice).

**Comment by tatarize** [comment]
Yeah, this was an issue in 0.5.2 it's already fixed in 0.6.0. So the issue will be closed when the update comes out.

**Comment by tatarize** [comment]
This issue was corrected in 0.6.0. Which is now in full release.
