### ISSUE TITLE
[0.8.2] Delete selected groups (tree) does NOT delete groups

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1760]
As I have stated before, the easy way to delete / remove is to remove **selected** items and their children and disregard emphasised.

**Comment by jpirnay** [comment]
Would be good if you could check that with the latest beta 0.8.3b2.
My test:
![grafik](https://user-images.githubusercontent.com/2670784/229881440-d9b5d2df-b931-404f-abb7-b9b480e76ed9.png)

Hitting delete:
![grafik](https://user-images.githubusercontent.com/2670784/229881553-5a5c9198-a5b8-41ca-811e-0a3983b28fec.png)

**Comment by Sophist-UK** [comment]
I assume you mean #1756 which I will test in the next day or two.

The right-click menus also need to be made clean and consistent so that a remove / delete option works the same regardless of the type(s) of node selected.
