### ISSUE TITLE
Blue laser trace remains on screen

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#178]
![2020-06-06 22_21_48-MeerK40t v0 5 2](https://user-images.githubusercontent.com/46349482/83953843-3776da80-a844-11ea-8730-715facdb8146.png)
Even after removing all files/elements/operations, the previous laser trace remains on screen.

**Comment by tatarize** [comment]
#58

**Comment by tatarize** [comment]
Yeah, I'm not sure what to do with that laser trace things. Pressing New will clear it in the next version. But, the overall utility is questionable and I'm not really sure what to do instead or whether to just clear that information a lot. It's just like a thousand lines between various position updates.

I'm not really sure what I should want done there or should do instead.

**Comment by tatarize** [comment]
Changing the selection will now clear that data. There's also a control to perform this action which could be bound to a keypress
