### ISSUE TITLE
[0.8.2] Move pane - Numeric Pad

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1789]
Is there any chance we can make the numeric pad "flow" i.e. horizontally next to the input boxes if there is room, otherwise below if there is room, else invisible? 

Or maybe have the numeric pad optional or have two versions with/without the numeric pad?

**Comment by jpirnay** [comment]
https://github.com/meerk40t/meerk40t/pull/1792

Will be suppressed if too narrow
