### ISSUE TITLE
In the navigation window, the rightmost square has no mouseover messages

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#179]
As the title states, there seem to be no mouseover messages for these buttons:
![2020-06-06 22_32_59-MeerK40t v0 5 2](https://user-images.githubusercontent.com/46349482/83954027-c2a4a000-a845-11ea-8233-b2cbf99d0565.png)

While they are very intriguing, I can't guess at what they do. Used for additional axis?

**Comment by tatarize** [comment]
Matrix transform operations for only changing the affine matrix on the selected design. Thought I had those too, but they must not made it in the final and gotten lost in the design bits somewhere. The ones on the left move, just the laser head. In the middle they move both laserhead and design, and on the right they only move the design (relative to the laser head for some of those operations).

Fixed it.
https://github.com/meerk40t/meerk40t/pull/160/commits/232310c26dda9eabc921833a549352591e6ac239

**Comment by tatarize** [comment]
This issue was corrected in 0.6.0. Which is now in full release.
