### ISSUE TITLE
[0.8.2] Group without inkscape label inherits from parent

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1790]
I am not sure if this is intentional or not. Should it use the id instead?

#### Meerk40t
![image](https://user-images.githubusercontent.com/3001893/230784241-f4b234aa-4726-4137-b2a1-62531ac80ad5.png)

#### Inkscape
![image](https://user-images.githubusercontent.com/3001893/230784268-a66e32e5-f16d-44a7-a1c0-561e042ca175.png)

**Comment by jpirnay** [comment]
Are these 'regular' groups or virtual copies via 'use'?

**Comment by Sophist-UK** [comment]
As you can see from the Inkscape screen shot, they are a mixture of real groups and clones, mostly real groups. But I didn't set the Inkscape label on them, so they are inheriting the parent label rather than saying e.g. "Group g5815 (2 children, 2 total)" or "Group use6217 (2 children, 2 total)".

But whilst we are talking about clones, it might actually be useful when MK converts a clone/use reference to a copy of the original to show this by prefixing the label with e.g. a "*" or dagger or similar.

**Comment by jpirnay** [comment]
I can confirm the issue but this requires a deeper change of the underlying logic as it involves amendments to [SVGElements](https://github.com/meerk40t/svgelements) which has a release cycle of its own.

**Comment by tatarize** [comment]
It actually shouldn't. It's not really that noted but as a subitem. The values also have "attributes" within the values and this is the dictionary of the tags that existed *on* that specific tag and *only* on that tag. So while the values are inherited from their parents if you check the values["attributes"] dictionary for the label in question you'll find it without the children being affected.
