### ISSUE TITLE
After File -> New, the last selection remains on screen

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#180]
![2020-06-06 22_35_35-MeerK40t v0 5 2](https://user-images.githubusercontent.com/46349482/83954071-28912780-a846-11ea-9c28-8b7f7b401cca.png)

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/commit/5dc914f766054cd3eb291f9a1c469ab1cb2a53c4 fixed.

**Comment by tatarize** [comment]
This issue was corrected in 0.6.0. Which is now in full release.
