### ISSUE TITLE
[Suggestion]: GRBL Reddot Laser Strength

### ISSUE THREAD

**Issue by dorsi90** [meerk40t/meerk40t#1860]
### Summary Description

Grbl reddot laser simulation with decimal places

### Current functionality

Currently reddot laser strength can have a integer value beetween 0 and 50%

### Future functionality

Reddot laser strength with decimal values like 0.10%
For some lasers 1% is high and it doesn't need as much power which also makes it less safe.
Lightburn for example has a range from 0% to 20% with decimal places so i think 50% is too big for all laser and unsafe to use.

### MeerK40t Version

0.8.4000

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by tatarize** [comment]
Addressed by #1863
