### ISSUE TITLE
[0.8.4] Convert to Path shown for existing Paths

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1874]
`element_path` is included as an object type @ [element_treeops.py#L2250](https://github.com/meerk40t/meerk40t/blob/master/meerk40t/core/elements/element_treeops.py#L2250)

**Comment by jpirnay** [comment]
A path converted to a path is actually a thing, as svgelements suffers from non resolved bug(s) around arc segments: this routines replaces contained arcs with cubic beziers.

**Comment by Sophist-UK** [comment]
Fair enough.
