### ISSUE TITLE
[0.8.4] Tree label DPI value does not change after changing DPI value from context menu 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1880]
May also not work from properties - not tested.

**Comment by jpirnay** [comment]
It does change for the main node but not its references in operations. Fixed.

**Comment by Sophist-UK** [comment]
I found this issue on Image nodes. Right click image, set DPI, not changed in label.

**Comment by tatarize** [comment]
confirmed works on image nodes
