### ISSUE TITLE
[Bug]: Kerf not working as expected

### ISSUE THREAD

**Issue by dorsi90** [meerk40t/meerk40t#1901]
### Summary Description

The kerf option not working as expected in some corners and also the path results distorted and also processing is very slow and requires a few minutes for this path

The picture below is with 0.2mm of kerf
![Screenshot (35)](https://github.com/meerk40t/meerk40t/assets/44925234/6aff412a-6299-4853-951e-39d0b38e1f3b)

The picture below is with 0.5mm of kerf
![Screenshot (36)](https://github.com/meerk40t/meerk40t/assets/44925234/86b5622e-c9d4-4a55-bf9c-817a40189737)

This is the test file
![drawingxx](https://github.com/meerk40t/meerk40t/assets/44925234/7bde4deb-df97-4705-85ec-a7ee1e4eca11)

### MeerK40t Version

0.8.4002

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by tatarize** [comment]
The comment was this seems really hard to fix and would require testing for artifacts in both directions and might get kicked to 0.9.x and run in numpy.
