### ISSUE TITLE
[0.8.4] Duplicate element - minor issues

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1916]
![image](https://github.com/meerk40t/meerk40t/assets/3001893/35a86000-1b75-4b96-a0bd-7bb45910567e)

1. Duplicate elements are shifted by exactly 3mm in both x and y directions.
2. Duplicate element labels wrong colour in operations part of the tree

**Comment by jpirnay** [comment]
1. Is by design to allow easier recognition, selection of the new elements

**Comment by Sophist-UK** [comment]
Fair enough.
