### ISSUE TITLE
[0.8.4] Bug: Dot Length setting still used even if checkbox is cleared

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1918]
For a vector (engrave) op, I checked the Dot Length checkbox and set a dot length of 20. Later I cleared the checkbox.

However, despite the checkbox being cleared I still got a dotted line instead of a solid line until I set the value back to 1.

**Comment by tatarize** [comment]
Confirmed. It uses dot_length rather than `implicit_dot_length` which takes into account actual custom.
