### ISSUE TITLE
[0.8.4002] Minor: Delete of Op (with Del key) deletes contents but not ops 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1936]

**Comment by tiger12506** [comment]
I believe that if you hit delete on it a second time it will then delete the op.
It's my understanding that this is the desired behavior. Not sure I personally agree that that's the way it should be.

**Comment by Sophist-UK** [comment]
Well, perhaps some people desire this behaviour, but clearly at least one person (me) doesn't. But that doesn't for a second mean I am right - just that there are differences of opinion.

**Comment by Sophist-UK** [comment]
This was definitely not completed as I had this issue today in the latest 0.9.5 beta.

As I said above, II (and apparently Tiger) think that the Delete key should operate consistently across all element types. But that is a personal preference and other opinions are equally valid - except that no one has actually expressed an alternative opinion.

**Comment by jpirnay** [comment]
It's not a bug it's a feature: have a look at the console output when you try to do that - it is using the ``tree selected delete``  command, that will tell you that it deliberately constrained the removal operation and offers you an alternative, too: ``tree selected remove`` that will delete the operation  and its content.
So i you are sure that you want that behaviour, then redefine the del-key

**Comment by Sophist-UK** [comment]
That is a how, not a why. The delete key could do a `tree selected remove` instead. It was a choice to use `tree selected delete` instead.

**Comment by jpirnay** [comment]
No it shouldn't - you opt for a dangerous operation as a default

**Comment by Sophist-UK** [comment]
Hardly a dangerous operation (deleting the Operation that you explicitly selected and then hit the delete key) especially when you can always use Undo.

Consistent UI actions are actually pretty important for creating a good experience for a user.
