### ISSUE TITLE
Crash on First Close for rPi and OSX.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#203]
File "meerk40t/Kernel.py", line 1484, in run
File "meerk40t/Kernel.py", line 1682, in run
File "meerk40t/Kernel.py", line 2085, in shutdown
File "meerk40t/Kernel.py", line 2102, in save_keymap_alias
wx._core.wxAssertionError: C++ assertion "szValue.empty()" failed at /Users/.../projects/bb2/dist-osx-py38/build/ext/wxWidgets/src/common/fileconf.cpp(920) in DoWriteString(): can't set value of a group!

First close can't set the name.

**Comment by tatarize** [comment]
This should be fixed circa 0.6.4. The error was the key "numpad\" which was registered as that key but the `\` looks like a path notation and created an issue there.

**Comment by joerlane** [comment]
Looks good on both Mac and rPi. now.
