### ISSUE TITLE
[0.9beta] Switching back and forth between 0.8 and 0.9

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2034]
Can you please save 0.9 settings to a different file from 0.8 (but still populate 0.9 using 0.8 settings if they exist)?

The issue is that people are likely to have different panel / pane sizes in 0.9 which means that when you switch back to 0.8 things look screwy and you have to tweak the sizes again.

Switching back and forth whilst 0.9 is in beta means that you will be continually tweaking panel and pane sizes.

**Comment by tatarize** [comment]
Hm. This seemed to happen between 6 and 7 and 7 and 8 but for different reasons. The expectation is that 9 should be basically the same thing as 8. Very little changed except the underlying geometric objects at their core were switched from svgelement.path to geomstr objects. There's been a few different feature changes and it's probably better to *just* reset the panel/pane stuff between the versions. For example just change the AUI perspective attribute value so you'd basically have all the gui stuff there setup differently and reset the panes (effectively the same as a reset panes in menu).

**Comment by tatarize** [comment]
Yeah, I've come around to this line of thinking. I'll change the AUI perspective attribute to make sure these don't save the same way.
