### ISSUE TITLE
[0.9] 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2036]
This is a:

*   [] Bug
*   [] Suggestion for an enhancement

## ERROR MESSAGE
```
<!-- Please copy and paste any error messages from e.g. a crash report file. -->
```

## YOUR ENVIRONMENT

*   MeerK40t version:
*   OS: 
*   Running from: <|-- e.g. Executable, package (PIP3/Pypi), downloaded source, git managed source

**Comment by Sophist-UK** [comment]
Apologies for the 4 (FOUR!!!!) empty issues I created. I have no idea what caused these, but it might have been the 2x kittens walking over my laptop keyboard LoL.

**Comment by tatarize** [comment]
lol
