### ISSUE TITLE
[0.8.9] Spool estimates double actual/simulation

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2056]
![image](https://github.com/meerk40t/meerk40t/assets/3001893/80bf49b2-a019-4b3d-a332-2499a019195c)

Raster
![image](https://github.com/meerk40t/meerk40t/assets/3001893/e0ed79cc-21a2-44c6-b7dc-c42e9eaa4a5a)
Cut
![image](https://github.com/meerk40t/meerk40t/assets/3001893/c6d6ea50-21b6-491e-bb19-0b4d429d11cb)
All
![image](https://github.com/meerk40t/meerk40t/assets/3001893/4aab8738-dd79-4850-85b4-8963941ca6b4)

**Comment by tatarize** [comment]
This is an addition. Am I wrong here?

Raster: 4:17
Cut: 3:37
Both: 4:17 + 3:37 = 7:54

**Comment by Sophist-UK** [comment]
@tatarize That addition is correct. However the spooler shows an estimate of 14:07 and **this** is what I am reporting.
