### ISSUE TITLE
[0.8.10] Duplicated image shows wrong size in tree label

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2086]
![image](https://github.com/meerk40t/meerk40t/assets/3001893/6440520e-b96b-473a-809f-7ce80f28c589)
I loaded a design, set the DPI to 500 and then duplicated the group the image was in. Whilst both images show the correct size in properties, the label is incorrect.

**Comment by jpirnay** [comment]
I can't reproduce the issue - is it still in place? And what does the label show - the original dpi / dimensions?

**Comment by Sophist-UK** [comment]
I am sure that it is still happening in 0.8.10 - why would it stop happening?

**Comment by jpirnay** [comment]
It's fixed in the 0.9.2 release but did not make it in time for the 0.8 bugfix release. Will be arriving there with the next 0.8 bugfix release cycle.
