### ISSUE TITLE
[0.8.10] Scene image dithering is often incorrect

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2087]
I haven't experimented enough with this to know when it doesn't correctly update the scene and apply image properties but I did note today that the image display changed significantly when I changed the DPI from 500 to 1000 and didn't change much when I changed it back.

I suspect that the image DPI is not applied when the the file (previously saved by MK with DPI set) is loaded.

**Comment by jpirnay** [comment]
That may have been the same root cause as in issue https://github.com/meerk40t/meerk40t/issues/2086. The same comment applies, not yet in place in the latest bugfix release but fixed in the codebase.
