### ISSUE TITLE
[0.9.2 Pre Beta 2] This was release as a full release and is being offered to 0.8 users!!!!!!

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2111]
I assume that offering it as a full release and not a pre-release was unintended.

**Comment by tatarize** [comment]
Ooof.

**Comment by tatarize** [comment]
The discord now has crash logs create discord entries for the crashes in the crash-reports forum. So the crash logs basically get pretty fast feedback. I was likely going to maybe nuke that version or not even offer the 0.9.2 beta line anymore which is probably better. At least until 0.9.1 is finished up.

**Comment by tatarize** [comment]
I also have Homeassistant have google home mini read off the title of any github issue raised.

**Comment by Sophist-UK** [comment]
Apologies then for the early enter on the other issue I just raised which had a mostly blank title and no description. 🤣 

I would keep the 0.9.2 pre-beta - just edit the tag and make it pre-release.

**Comment by tatarize** [comment]
Yeah, just that the 0.9.2 stuff is a bit useful but a bigger change than I would want in 0.9.1 (moves to views away from matrices there).

**Comment by Sophist-UK** [comment]
Exactly!
