### ISSUE TITLE
[0.8.12] Combined path rendered/burned incorrectly

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2199]
#### Inkscape
![image](https://github.com/meerk40t/meerk40t/assets/3001893/9f8ee49a-e7c6-44ae-a5d6-201b00505ce3)

#### Meerk40t 0.8.12
![image](https://github.com/meerk40t/meerk40t/assets/3001893/14148830-40a9-4c7b-8737-35280efdf2ce)

**Comment by jpirnay** [comment]
We may need the culprit svg file to understand the issue
