### ISSUE TITLE
[0.8.12] Unexpected Scene artifacts 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2232]
Nothing is selected:
![image](https://github.com/meerk40t/meerk40t/assets/3001893/490d630c-5498-4ff1-9352-7e226c2eea65)

As you zoom in and out (using the Ctrl+mouse wheel) the artifacts change.

**Comment by tatarize** [comment]
Odd. I assume it's something with the scale at different times but, certainly strange.
