### ISSUE TITLE
[0.8.12] Tree context menu to (completely) delete elements selected in Ops

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2233]
Multiple elements selected:
![image](https://github.com/meerk40t/meerk40t/assets/3001893/ae4c2040-8ec9-4e4f-859a-201307c3d622)

Single path selected ("Delete element, as selected in the scene" missing):
![image](https://github.com/meerk40t/meerk40t/assets/3001893/3a8a5928-17f0-49bc-a689-016e8dd54ff4)

**Comment by tatarize** [comment]
That does seem to be a little inconsistent.
