### ISSUE TITLE
[Suggestion] No redo function

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2261]
If I am `undo`ing several changes (which works GREAT) and I undo one or two steps too far, I would like to `redo`.

In the array you use to hold the history, can you do an undo by moving a pointer back from the end, allowing redo to move the pointer forward again, and when you change something then truncate the array and append the latest change?

**Comment by tatarize** [comment]
Why doesn't that already work? Does the `redo` button not work?

**Comment by tatarize** [comment]
![image](https://github.com/meerk40t/meerk40t/assets/3302478/d62f6ed9-ce36-4a94-8da4-8316707e2316)

vs. 

![image](https://github.com/meerk40t/meerk40t/assets/3302478/291f81a2-674d-433c-9276-daf710ccc6f1)

**Comment by Sophist-UK** [comment]
Oops. Sorry.
