### ISSUE TITLE
Post-File Load Movement

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#2277]
SVGs load natively per-spec in the upper left corner.

Add a feature that after you load a design.  You tell it, what corner of that design you care about. And where that corner should be located and on file load it should move the object's corner to that location. So you could tell everything to load up 1in 1in from the start point. Or tell everything to load centered.

**Comment by jpirnay** [comment]
We have now (since 0.9.5b3) a simplified version of this: hold the shift-key down when picking the file to load and will be offered an option where to put the content.

**Comment by jpirnay** [comment]
Xload has this feature
