### ISSUE TITLE
[0.9.4b1] UI review

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2328]
UI is "getting there" but is still rubbish in some significant areas.

Overall the UI is very crisp, and the calling of the ribbon bars is pretty well perfect, however we still have terrible scaling issues with many of the panes on the right. (Was this scaling ever tested properly?)

![image](https://github.com/meerk40t/meerk40t/assets/3001893/f6e5cb12-1a32-4121-9ac0-4a0432b38c1a)

**Comment by Sophist-UK** [comment]
P.S. The tabs on the Laser pane seem to have changed position for no apparent reason. IMO the 0.8 tab order was close to ideal. Jog and Move tabs are related and should be next to each other, and the optimise and plan tabs should be next to the Laser tab because the Laser tab has an Optimise check box (Laser / Optimise / Plan is the logical order IMO).

**Comment by tatarize** [comment]
You can drag the panel over if you want. Generally these are based on, in part, how often they were being used. While `plan` was certainly used less than jog. Admittedly `optimize` is probably used less than `move`. It is the case that I generally used `laser` and `jog` basically always but rarely use the other ones.

**Comment by tatarize** [comment]
Yeah, we tested the sized icons. They don't seem to do that on my setup. And I'm not entirely sure how you got them to do that.

**Comment by jpirnay** [comment]
No idea, how you arrive at getting that phenomenon - I assume it's your MS Surface device? What settings have you chosen for iconsize in Preferences - GUI:
<img width="246" alt="image" src="https://github.com/meerk40t/meerk40t/assets/2670784/2d596d03-e33f-456e-b2b1-cf23e083124c">

This is what I end up with with Large - Default - Tiny:

<img width="154" alt="iconsize_large" src="https://github.com/meerk40t/meerk40t/assets/2670784/3d141cad-ec04-472f-a6a9-c2e211c84d41">
<img width="155" alt="iconsize_default" src="https://github.com/meerk40t/meerk40t/assets/2670784/04bd04c6-9608-441c-9ac6-ad00abe5041d">
<img width="154" alt="iconsize_tiny" src="https://github.com/meerk40t/meerk40t/assets/2670784/2f99dfef-3899-4bd1-9f9a-4edac8d1a261">

Still the jog-buttons should be fully scalable:
<img width="102" alt="jog_0" src="https://github.com/meerk40t/meerk40t/assets/2670784/420b0c96-3109-47bb-a5ad-0558e5021b9a">
<img width="148" alt="jog_1" src="https://github.com/meerk40t/meerk40t/assets/2670784/4d94b0a6-eb87-4794-86cb-28a9a094ebee">
<img width="305" alt="jog_2" src="https://github.com/meerk40t/meerk40t/assets/2670784/3fa83f3b-cb10-46e9-8b49-693d9a365c5d">

**Comment by Sophist-UK** [comment]
Icon size: Default

Also, `Preferences/Ribbon/Show the Ribbon Labels` is greyed on on `tools` and not on `primary` - I think this was to avoid duplication with `Preferences/GUI/Show the Ribbon Labels` and the enable/disable is the wrong way around. (As a consequence knickers get in a twist if you disable/enable primary Ribbon Labels on the Ribbon tab.

It could be the DPI screen resolution on my Surface Pro 3 or Windows display settings.
![image](https://github.com/meerk40t/meerk40t/assets/3001893/244cce63-670d-490d-8b78-bac67b8f4017)
![image](https://github.com/meerk40t/meerk40t/assets/3001893/fd404176-ec92-44ec-8ca2-d7cd7bb3075e)

**Comment by Sophist-UK** [comment]
Running this beta on my normal PC, the big button icons scale fine, but the Laser and Position panels are screwy:
![image](https://github.com/meerk40t/meerk40t/assets/3001893/0c9a42ad-1f0e-49e2-b2ec-e7f3b89faf67)
1. Laser pane example - X and Y boxes should be smaller, the buttons bigger generally and the gaps between the 9 buttons on the right should not scale at all i.e. gaps constant size.
2. Position pane - the icon with the 9 separate boxes is so small that it is almost impossible to click on the correct box!!

Definitely not yet suitable for production.

**Comment by jpirnay** [comment]
Have you set iconsize to tiny or small?

**Comment by Sophist-UK** [comment]
No - as stated before, Iconsize=Default.

However with SVG icons the scaling should be automatic and not need an Iconsize GUI option.

**Comment by jpirnay** [comment]
I was finally able to get an idea why this scaling issue appeared. It seems to be an issue with ``wx.BitmapBundle`` providing a wrong ``GetDefaultSize`` for a bitmap under Windows with a scaling factor beyond a certain value (I had to go to 250% to see it).
```
        best_size = max(best_size, 20)
        border = 2
        bmp = self.icon.GetBitmap(color=self.fgcolor, resize=best_size, buffer=border)
        s = bmp.Size
        self.button_go.SetBitmap(bmp)
        bmp = self.icon.GetBitmap(resize=best_size, buffer=border)
        self.button_go.SetBitmapFocus(bmp)
        t = self.button_go.GetBitmap().Size
        print(f"Was asking for {best_size}x{best_size}, got {s[0]}x{s[1]}, button has {t[0]}x{t[1]}")
        scalex = s[0] / t[0]
        scaley = s[1] / t[1]
        if abs(1 - scalex) > 1e-2 or abs(1 - scaley) > 1e-2:
            print(f"Scale factors: {scalex:.2f}, {scaley:.2f}")
```
provides:
```
Button has Size: (930, 771), panel has size (930, 771), client: (930, 771)
Was asking for 711x711, got 711x711, button has 2133x2133
Scale factors: 0.33, 0.33
```
I have no idea how to prevent it, but I can do a second pass doing a smaller picture, that will create the icon at a smaller resolution which will consequently scale the thing up to the desired size.

**Comment by jpirnay** [comment]
On my system 150% user scale works without issues, beyond 175% the stored images is twice as big as expected, beyond 250% 3 times as big...
