### ISSUE TITLE
Tool path veers off the working area. 

### ISSUE THREAD

**Issue by alula-fpv** [meerk40t/meerk40t#238]
with the .svg file I downloaded from somewhere, the job path tries too veer off the working area as there are some dots/points in the drawing(on meerk40t) which is apparently not noticeable on inkspace. Is it possible to limit the tool path within the working area and show warnings/error if there are drawings beyond the working area when executing the job? 
Thanks

[Base.zip](https://github.com/meerk40t/meerk40t/files/5331420/Base.zip)

**Comment by tatarize** [comment]
Yeah, there was a plan to make it show an those in red text if they existed and I could certainly add them to the 0.7.0 list. There's some cases where it might be valid, but mostly it would just ram the laserhead into the wall.
