### ISSUE TITLE
[Bug]: Perform simple trace around selection

### ISSUE THREAD

**Issue by kostex** [meerk40t/meerk40t#2407]
### Summary Description

(Always using the latest release)

The Perform simple trace around selection, traces around ALL objects, not "selected".
If this is somehow correct behaviour, then please respect active/inactive/hidden mode.
Hope you can help!
Thanks!

Roel

### MeerK40t Version

v0.9.4 B2-2

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by jpirnay** [comment]
Thank you for your comment.
- The buttons in the navigation / laser panel will always consider *all* elements.
- You can use the console to restrict the to be considered elements to the selection by issuing ``trace hull`` - that will only consider the selection.
- As of now, the element status (unassigned / contained in an inactive operation) was ignored. The code base has been updated with your suggestion to take this status in account and exclude these from the laser hull movement [Commit](https://github.com/meerk40t/meerk40t/commit/95ee9350ebe619aa0b591bfb19e3e9c6c60f46f5)
