### ISSUE TITLE
fillet not showing properly in .dfx file

### ISSUE THREAD

**Issue by gyan007** [meerk40t/meerk40t#241]
radius and direction of some of the fillet changes when the .dfx file is loaded onto meerk40t_v0.67
[CameraSlider.zip](https://github.com/meerk40t/meerk40t/files/5354774/CameraSlider.zip)

**Comment by tatarize** [comment]
Yeah that's wrong. Will check.

**Comment by tatarize** [comment]
This is corrected in #254
