### ISSUE TITLE
[Suggestion]: Add Raster/Engrave/Cut Operations to Material Editor

### ISSUE THREAD

**Issue by kostex** [meerk40t/meerk40t#2425]
### Summary Description

Either I don't know how or the feature is missing:
I'm creating a material database but cannot find a way to add an operation to a material.
If I want to add a Cut, Engrave or Raster operation to the list of operations, to my knowledge there is no way.

![image](https://github.com/meerk40t/meerk40t/assets/11047825/5927ab3d-e4ac-4531-a466-b106d0316229)

### Current functionality

Create a List of operations outside of the material editor and import them.

### Future functionality

Right click and add Raster, Engrave and or Cut operation in the material library editor

### MeerK40t Version

Latest commit

### MeerK40t Type

Git

### Your Operating System

Windows

**Comment by jpirnay** [comment]
The way to allow full fledged editing of the material database entry is to load the set into the tree, edit it there with all the regular features and then to reapply the tree content to the material entry.

**Comment by jpirnay** [comment]
Added some functionalities
