### ISSUE TITLE
[Bug]: Edit nodes: Nodes do not snap to grid

### ISSUE THREAD

**Issue by kostex** [meerk40t/meerk40t#2437]
### Summary Description

When snap is on, nodes do not snap to grid in edit mode.
![snap](https://github.com/meerk40t/meerk40t/assets/11047825/7bed46c3-56ed-4cbb-9ba6-a600dc8c0f6d)

### MeerK40t Version

Latest commit

### MeerK40t Type

Git

### Your Operating System

Linux

**Comment by jpirnay** [comment]
Addressed in https://github.com/meerk40t/meerk40t/commit/f702dc4cd4e78cbde414e080c4cc2f5045dcdca6

**Comment by kostex** [comment]
Something still is off.. I would presume that whenever a grid point has a green cross the node will snap when clicked, but that is not what happens.. zooming in and out feels like it changes the threshold too.
Adding curved points by holding the left mouse button and dragging, NEVER snaps to a grid point.
Hope I'm explaining it correctly.

Cheers!
![snap](https://github.com/meerk40t/meerk40t/assets/11047825/c77d7108-8629-462e-a7a0-c0365c8b932e)

**Comment by jpirnay** [comment]
Vector tool seems to be the last pocke t of resistance - not understood why at the moment

**Comment by Sophist-UK** [comment]
> the last pocket of resistance

It's those plucky Ukranian resistance fighters putting up a fight against the forces trying to exterminate them. 😄
