### ISSUE TITLE
Fonts not showing properly

### ISSUE THREAD

**Issue by gyan007** [meerk40t/meerk40t#247]
the fonts geometry changes when it is opened in meerk40t. 
[K.zip](https://github.com/meerk40t/meerk40t/files/5399100/K.zip)

**Comment by tatarize** [comment]
#183 notes this.
#61 is the original issue.

This is completely accurate. I need to go over that work and do some work to make it load the same font correctly each time. As well as some other work to convert the fonts to vector objects which is currently not a thing it does. Perhaps using FreeType.py or other such library.

**Comment by tatarize** [comment]
See #61
