### ISSUE TITLE
[Suggestion]: Air assist as an option for given operation

### ISSUE THREAD

**Issue by FelixEL** [meerk40t/meerk40t#2487]
### Summary Description

Some operations work better with air assist switched on (cutting) and some with off (engraving). @jpirnay  implemented a very good backbone of air assist with all the features needed for global air assist.

I started to work on a way to enable this feature for selected operations:  

![obraz](https://github.com/meerk40t/meerk40t/assets/30323886/ae0634a5-a1f3-445b-80ec-50cb07a25e52)

This option will be also available form operation properties menu (double click on operation):
![obraz](https://github.com/meerk40t/meerk40t/assets/30323886/00404c5a-bf66-492d-b015-4e8c233959f8)

### Current functionality

Currently air assist can be set to on or off for all operations at once as part of configuration:
![obraz](https://github.com/meerk40t/meerk40t/assets/30323886/ae07c8b4-4f7f-4d69-9f96-8eeeaf949466)

### Future functionality

Enabling air assist for selected operations - engraving - off, cutting - on etc. (user can do selection according to own needs).
Global air assist override (the one from configuration) - it makes sense to keep exit action (for example switch off air assist after all operations). Entry action related to air assist will be overridden with first operation specific air assist settings

### MeerK40t Version

86c8c45

### MeerK40t Type

Git

### Your Operating System

Windows

**Comment by jpirnay** [comment]
Sounds legit, although you would need to have three states per laser operation: turn on - turn off - keep the existing state.
I will work on it.

**Comment by FelixEL** [comment]
@jpirnay Sounds cool! I like idea of three state approach. Feel free to cherry-pick from my devbranch 

https://github.com/FelixEL/meerk40t/tree/airassist_grbl

I did some work (mostly GUI and callbacks). I was trying to figure out command injection for particular operation but couldn't find documentation how its done.

**Comment by jpirnay** [comment]
Implemented and integrated in current main
