### ISSUE TITLE
[Bug]: M3-NANO fails with move commands

### ISSUE THREAD

**Issue by ezequielleonzybert** [meerk40t/meerk40t#2490]
### Summary Description

board: M3-NANO
Depending on the move value or move_absolut value, the command does nothing. It works with integers values but sometimes decimals makes it does nothing. This was talked on discord server and Tat told me how to solve this. I edited the code in "lihuiyu/driver.py" to change every "S1P/n" string to "S1PF/n". And now it's working, but I don't know if this is the correct solution neither how to do a pull request. So I leave this issue here. Thanks.

### MeerK40t Version

9.4

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by jpirnay** [comment]
Addressed in PR 2491

**Comment by Sophist-UK** [comment]
Reposting the PR #2491 so it is linked.
