### ISSUE TITLE
Excessive amount of computer memory. [Bug]: 

### ISSUE THREAD

**Issue by manuel1414** [meerk40t/meerk40t#2502]
### Summary Description

On Mac. From version 0.8 to the latest, 0.9.4, the app has been consuming an excessive amount of computer memory, reaching up to 4GB for a simple rasterization task.
![Captura de pantalla 2024-06-05 a la(s) 14 13 32](https://github.com/meerk40t/meerk40t/assets/31073985/b4047fd3-9b95-44a5-a767-5c555e664f6b)

### MeerK40t Version

0.9.4

### MeerK40t Type

Executable

### Your Operating System

Mac (before M1/Bigsur)

**Comment by jpirnay** [comment]
Would be helpful to have the specifc file that causes this
