### ISSUE TITLE
[Suggestion]: Overlay the major version i.e. 0.9 onto the MK executable icon

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2562]
### Summary Description

As title to help distinguish shortcuts / executables in the taskbar.

Because changing from 0.8 to 0.9 is rare this would have low overhead.

### MeerK40t Version

0.9.4

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by jpirnay** [comment]
Will be integrated on top of 128x128 and 256x256 icons
