### ISSUE TITLE
[Bug] 0.9.5b6 Tree branch open/close requires double click not single click

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2569]

**Comment by jpirnay** [comment]
Can't be recreated

**Comment by jpirnay** [comment]
The wxPython TreeCtrl does not expose the usual left mouse click events, so that we could do a manual hit test and establish wehther it's near a node or not - so unfortunately no (and I tried for the better part of an hour to look for a workaround).

**Comment by Sophist-UK** [comment]
So perhaps it is a wxPython or wxWidgets bugette then...

**Comment by Sophist-UK** [comment]
Not occurring today on 0.9.5b8.
