### ISSUE TITLE
problem with fillet in .dfx again..

### ISSUE THREAD

**Issue by gyan007** [meerk40t/meerk40t#257]
some fillet not showing properly in meerk40t_v_0.6.10
[PlantPot.zip](https://github.com/meerk40t/meerk40t/files/5494305/PlantPot.zip)

**Comment by tatarize** [comment]
Yeah, bottom right hand corners in the dfx are clearly swept the wrong direction. 

![meerk40t-dxf](https://user-images.githubusercontent.com/3302478/98994538-d46d2c00-24e4-11eb-82c1-5babbb651570.png)

**Comment by tatarize** [comment]
This is fixed in the dev branch and will be final corrected when 0.6.11 goes live.

**Comment by tatarize** [comment]
This was done improperly for dxf: "ARC goes always from dxf.start_angle to dxf.end_angle in counter clockwise orientation around the dxf.extrusion vector, which is (0, 0, 1) by default and the usual case for 2D arcs."

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.6.11-beta-1

This should have the code corrected. I'll be a bit for @joerlane to review and approve, but it basically is just a couple very minor bug fixes.

**Comment by gyan007** [comment]
@tatarize Thanks a lot!
