### ISSUE TITLE
[Suggestion]: add a Special Operation to turn on Live/Trace

### ISSUE THREAD

**Issue by Eszartek** [meerk40t/meerk40t#2574]
### Summary Description

It would be handy to be able to add a special operation at the end of the tree to turn on the Live/Trace feature. I find, as a work flow, I constantly turn on Live Bounds prior to engraving, especially when testing parameters and moving the work piece between tests. 

### MeerK40t Version

v0.9.4060

### MeerK40t Type

Executable

### Your Operating System

Linux

**Comment by jpirnay** [comment]
You already have that functionality: right click at the operations part of the tree and pick from the context menu:
_Append special operation - Append console_
Set the command to: ``full-light``
The command to stop the trace would be ``stop``
