### ISSUE TITLE
[Suggestion] 0.9.5b6 Warning symbol shows when operations are deliberately disabled.

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2581]
This is usually a deliberate action... (and I don't want to see this)
![image](https://github.com/user-attachments/assets/5b1c859f-c80e-4a7d-8547-4f4f7a053677)

But on the other hand elements not associated with an operation is often a mistake... (and I do want to see this)
![image](https://github.com/user-attachments/assets/b8f85d59-113a-4a06-80a5-cef6c37328d3)

**Comment by jpirnay** [comment]
Feature request
![grafik](https://github.com/user-attachments/assets/d78527c9-b802-4945-b796-1e5fc439c374)

**Comment by jpirnay** [comment]
It always did: https://github.com/meerk40t/meerk40t/commits/main/meerk40t/gui/gui_mixins.py
But that's irrelevant as you can now set the cutoff threshold:
-Critical: anything that can harm your laser, ie bumping into rails
-Normal: anything that can spoil your burn, ie non-assigned elements
- Low: anything, that can spoil your burn, but you did it intentionally, ie disabled operations, hidden elements

```python
        self._concerns.clear()
        max_speed = getattr(self.context.device, "max_vector_speed", None)
        if has_ambitious_operations(max_speed, ("op cut", "op engrave")):
            self._concerns.append(
                (
                    _("- Vector operations are too fast.")
                    + "\n  "
                    + _("Could lead to erratic stepper behaviour and incomplete burns."),
                    CONCERN_CRITICAL
                )
            )
        max_speed = getattr(self.context.device, "max_raster_speed", None)
        if has_ambitious_operations(max_speed, ("op raster", "op image")):
            self._concerns.append(
                (
                    _("- Raster operations are too fast.")
                    + "\n  "
                    + _("Could lead to erratic stepper behaviour and incomplete burns."),
                    CONCERN_CRITICAL
                )
            )
        if has_objects_outside():
            self._concerns.append(
                (
                    _("- Elements are lying outside the burnable area.")
                    + "\n  "
                    + _("Could lead to the laserhead bumping into the rails."),
                    CONCERN_CRITICAL
                )
            )
        flag, info = has_close_to_edge_rasters()
        if flag:
            self._concerns.append(
                (
                    _("- Raster operations get very close to the edge.")
                    + "\n  "
                    + _("Could lead to the laserhead bumping into the rails.")
                    + "\n  "
                    + info,
                    CONCERN_NORMAL
                )
            )

        non_assigned, non_burn = self.context.elements.have_unburnable_elements()
        if non_assigned:
            self._concerns.append(
                (
                    _("- Elements aren't assigned to an operation and will not be burnt"),
                    CONCERN_NORMAL
                )
            )
        if non_burn:
            self._concerns.append(
                (
                    _(
                        "- Some operations containing elements aren't active, so some elements will not be burnt"
                    ),
                    CONCERN_LOW
                )
            )

        non_visible, info = has_hidden_elements()
        if non_visible:
            self._concerns.append(
                (
                    _("- Elements are hidden and will not be burnt") + f" ({info})\n",
                    CONCERN_LOW
                )
            )

```

**Comment by Sophist-UK** [comment]
I just had unclassified elements **and** a disabled op and because I was expecting the warning for the disabled op, I did a burn with missing elements!!!!

**Comment by jpirnay** [comment]
Warninglevel needs to be critical+normal

**Comment by Sophist-UK** [comment]
I don't understand that. I guess I need some explanation as to what each means, and what selecting them means because it is completely unclear at the moment.

**Comment by Sophist-UK** [comment]
![image](https://github.com/user-attachments/assets/850636f9-e6b1-43bf-9caf-78fbaf80cdd8)

I thought this was working yesterday, but today not.

I changed it bac to critical and reclassified. Then back to Normal+Critical and reclassified. Then took the screenshot.

**Comment by Sophist-UK** [comment]
Warning symbol needs to be recalculated (event triggered) when the preference dropdown is changed.

**Comment by jpirnay** [comment]
Thank you for your comment, this has already been implemented in PR #2613

**Comment by Sophist-UK** [comment]
Can we please improve the tooltip in Preferences / GUI to explain what Low, Normal & Critical actually mean?

**Comment by Sophist-UK** [comment]
Still wrong in 0.9.4080:
![image](https://github.com/user-attachments/assets/fa85772b-053f-4f2c-b4ce-9f6e53c77604)

And no definitions of what `Critical`/`Normal`/`Low` mean.:
![image](https://github.com/user-attachments/assets/2fb505e6-bd26-445f-ae27-2da1dcebd003)

**Comment by Sophist-UK** [comment]
Code here does not appear to take account of the UI settings: https://github.com/meerk40t/meerk40t/blob/061c80507c79e6ef2919ee1bc7de597cdcc6e458/meerk40t/gui/wxmtree.py#L1079-L1093
