### ISSUE TITLE
[Bug] 0.9.5b6 Regmarks duplicated when you reload a file.

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2598]

**Comment by jpirnay** [comment]
Acknowledged, but unfortunately there's no easy fix for that that does not have certain drawbacks.
Invisible nodes, ie regmarks will be moved to the regmark branch on load. They are losing then any connection to the filenode that is created under elements. The only option would be to create another filenode under the regmarks branch but would require that we need to loop through all other filenodes with the same filename and delete these too. 
Again feasible, but it would mean that if you load the same file multiple times (which is fully allowed and supported) that you would then delete all occurences and only reload one.

You could argue that is okay, but you could equally argue it's not.

Attached the implementation as in branch ``reload_regmarks``
![regmark](https://github.com/user-attachments/assets/732de281-05d5-4aed-9016-ba33857825bb)

**Comment by Sophist-UK** [comment]
I would argue that just because elements are invisible in the SVG doesn't make them Regmarks.

I would personally like to see the hidden/visible attribute kept when the file is loaded and so all elements are in the tree, with the hidden ones e.g. greyed out - and a context menu option to make visible or hide elements. 

If I want to take a hidden element and classify it as a Regmark, then I should be able to do so (with it being a link like that between elements in ops and their original, perhaps with a file node as shown above - and saved in the same way as it currently is for ops so that when you reload after saving the file you get the Regmarks back again).

We might also have a standardised rule for a particular element colour to make it auto classify as a regmark.

**Comment by jpirnay** [comment]
Regmarks are saved and reloaded already. The main difference between regmarks and "invisible" elements (which we have but do not save/load) is the option to still see them faintly as indicator. A complete rehaul of the logic is not something I will entertain lightly - not only because it would be time consuming but as well as mutiple workflows with different preferences are in existence.

**Comment by Sophist-UK** [comment]
Yes - I understand the effort that would be involved, but invisible elements didn't used to be treated as Regmarks.

(As an aside, the Delete key doesn't work as it should with regmarks either.)

**Comment by jpirnay** [comment]
Regmarks are in place since more than 2.5 years... Inkscape layers had never been recognized, that's in place since more than 9 months.

**Comment by jpirnay** [comment]
> (As an aside, the Delete key doesn't work as it should with regmarks either.)

Acknowledged and fixed - irrespectively of the other discussion
