### ISSUE TITLE
[Bug] 0.9.5b7: Many (if not all) Tree context changes not saved separately in Undo list

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2606]
so a single Undo results in many operations being undone

**Comment by jpirnay** [comment]
> Note: if #2571 was implemented it would make it much easier to see whether an action has made it onto the undo list or not.

Has been implemented in PR #2580

**Comment by jpirnay** [comment]
Addressed in PR #2628

**Comment by Sophist-UK** [comment]
Much better in 0.9.5b8 however Ungroup on a File node isn't saved in the Undo list.
