### ISSUE TITLE
0.9.5b8: New icon on windows taskbar needs white background for dark themes

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2608]
![image](https://github.com/user-attachments/assets/2daa96f5-0c7a-4fbd-907f-9a5e18d2b438)

Super-mk does not stand out. Background inside circle needs to be white, circle probably needs to be contrasting colour like red.

**Comment by Sophist-UK** [comment]
Windows 10 dark theme.

MK pinned to taskbar but *not* opened i.e. shortcut icon:
![image](https://github.com/user-attachments/assets/f62c3367-91bb-444a-98c0-569c54dc749a)

MK opened i.e. executable icon:
![image](https://github.com/user-attachments/assets/b94a4cca-3368-4783-9cdc-560cc9673d21)

The contrast on both of these is not great. Unopened it is white on white. Opened it is black/white on grey.

In both cases, my recommendation is to:

* Shortcut icon: Make the Meerkat Black with red eyes just like the execution icon
* Both icons: Make the circle red - and perhaps a tiny bit thicker - and fill with white background inside the circle to give contrast with meerkat and laser-eyes and circle.
* Both icons: Background outside the circle either transparent or black or dark grey.

**Comment by Sophist-UK** [comment]
Sorry - still not great in 0.9.5.3:
1. Icon when running too small and so it is VERY indistinct - it really does not do the brand recognition thing that it needs to do. I provided the Discord icon for comparison.
![image](https://github.com/user-attachments/assets/92e58548-92b2-4811-95d0-2defedcc352c)
2. The shortcut icon is a better size, but the MK body is white rather than black.
![image](https://github.com/user-attachments/assets/cfaf22c9-f293-41a7-bc7c-99700ba4391a)

**Comment by jpirnay** [comment]
Look at the one on github and validate your findings

**Comment by Sophist-UK** [comment]
Which one on Github? If you mean you want me to run from source, then sorry - but after I left the development community due to being abused I deleted my development environment.

But the above graphics are on the absolute latest executable from only last week.
