### ISSUE TITLE
0.9.5b8: Feedback on new tree context menus after #2619

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2639]
@jpirnay Jens

#2619 was an excellent improvement and the code looks very elegant too.

A few comments on the menus as they now look:
### General
* Most menu items are Sentence ***c***ase - but a few are Title ***C***ase
* Many status bar hints are missing when you hover over a context menu
### Operations top-level node
![image](https://github.com/user-attachments/assets/2334f5ea-5a0f-44f3-8132-32866c179277)
* Global ***S***ettings - Not clear what these are from the name - Global operations properties?
* Classification –duplicate entry for Refresh classification for all - 
   ![image](https://github.com/user-attachments/assets/0fbedd93-791c-458e-b1d8-719f6e9f231f) 
* Scale Speed/Power Settings - Name and submenu contents are conflicting - menu says "Scaling" suggesting that this scales the speeds or powers set on individual operations but sub-menu talks about Maximums.

### Image operation node
![image](https://github.com/user-attachments/assets/747088a2-c168-48eb-879b-1af843eb9637)
* (For all operations nodes) Duplicate element(s)/operations - Perhaps in the same menu group?
* (For all operations nodes) Duplicate element(s) - not actually duplicating the elements themselves - more like Duplicating operation's burns on those elements

### Raster operation node
![image](https://github.com/user-attachments/assets/952eec65-c20d-410a-9cde-99c789810387)
No additional comments

### Engrave operation node
![image](https://github.com/user-attachments/assets/35344f29-dc3a-4539-b5ab-4065569bf222)
No additional comments

### Cut operation node
No additional comments

### File elements node
1. Toggle Visibility on File node doesn't do anything.

### Shape elements node

NOTE: Full description to be completed.

**Comment by jpirnay** [comment]
Addressed in PR #2640 

1.     Case of menu items aligned unless the term has a special meaning like Cut or Raster
2.      Help text content added for all items
3.      Some terms changed to provide more clarity for certain menu items 8GLobal ops properties, Scale speed / power)
4.      The menu items for an element under an operation consist of the reference specific and underneath those belonging to the referred element. These two can't be easily mixed without addtional refactoring.

**Comment by Sophist-UK** [comment]
4. Not sure which item I reported that this relates to, but all of my comments were language related and not functionally related.
