### ISSUE TITLE
[Suggestion] 0.9.5b8: Splashscreen

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2643]
I absolutely love the splash screen but IMO...
   ![image](https://github.com/user-attachments/assets/45253ee7-526b-4e47-a137-f0c2f1dba4ee)

1. It would be even better with the word "Meerk40t" incuded.
2. It would be even better with the version overlayed in the bottom RH corner.

**Comment by jpirnay** [comment]
The text part of the screen does display Meerk40t plus version information in the beginning - I could display it all the time throughout the startup phase

**Comment by Sophist-UK** [comment]
I don't see any words or versions when loading on Windows. Sorry.

**Comment by jpirnay** [comment]
Hmm, don't you see this:
![start](https://github.com/user-attachments/assets/6c0be7f0-80ec-48bd-8515-5b327792773a)

**Comment by Sophist-UK** [comment]
No - the original pic I posted is all I see.

**Comment by jpirnay** [comment]
Being displayed and confirmed as working.
