### ISSUE TITLE
[Bug]: Color themes broken in recent commits

### ISSUE THREAD

**Issue by Laserology** [meerk40t/meerk40t#2665]
### Summary Description

I don't know since when, but the latest commits have broken color themes. They no longer use the colors specified in the default profile, and they do not save when a user changes them and reopens the program.

### Additional Details

Odly-pickeed colors are now used for Bed, grid, etc...

### Crash logs

```shell
N/A
```

### MeerK40t Version

v0.9.5 git - latest commit

### MeerK40t Type

Git

### Your Operating System

Linux

**Comment by Laserology** [comment]
Top bar buttons also no longer follow the requested icon size
![Screenshot_20241023_130506](https://github.com/user-attachments/assets/f611294c-3527-4cad-a80e-f079a38506fe)

**Comment by jpirnay** [comment]
> Top bar buttons also no longer follow the requested icon size

The buttons in the ribbon bars (top + left) scale automatically. The setting for icons is about the icons in the regular buttons

**Comment by jpirnay** [comment]
> Odly-pickeed colors are now used for Bed, grid, etc...

Those were from your PR - I don't like them either

**Comment by jpirnay** [comment]
The saving / loading bug is acknowledged and fixed

**Comment by jpirnay** [comment]
The ugly defaults for black mode remain

**Comment by Laserology** [comment]
> > Odly-pickeed colors are now used for Bed, grid, etc...
> 
> Those were from your PR - I don't like them either

I don't recall ever changing the bed to a purple color... I changed it to use different menu colors that would blend into the system, not stick out like a sore thumb

**Comment by Laserology** [comment]
> > > Odly-pickeed colors are now used for Bed, grid, etc...
> > 
> > Those were from your PR - I don't like them either
> 
> I don't recall ever changing the bed to a purple color... I changed it to use different menu colors that would blend into the system, not stick out like a sore thumb

Can you point to a specific change where I set this?

**Comment by jpirnay** [comment]
![grafik](https://github.com/user-attachments/assets/f86ba5ef-f025-4fc3-a6d0-d8a56b3c2c9c)

**Comment by Laserology** [comment]
> ![grafik](https://github.com/user-attachments/assets/f86ba5ef-f025-4fc3-a6d0-d8a56b3c2c9c)
> 
> 

When I tested that, it worked just fine. Are you sure nothing else changed?

**Comment by Laserology** [comment]
I see now somebody added 'tohex()'... Is that needed? I didn't have any issues when I tested originally

**Comment by Sophist-UK** [comment]
I cannot believe that it is me saying this, but let's try to remember that we are all of us human and can make mistakes or write imperfect code - and that we all have a common goal, to make MK better and better. So it might be better to worry more about how to fix something that has gone wrong, and less about who caused it to go wrong.

**Comment by jpirnay** [comment]
It's partly you and partly me: your code crashed on non linux and i added the hex - but its wrongly coded. Just fixing it

**Comment by Laserology** [comment]
> I cannot believe that it is me saying this, but let's try to remember that we are all of us human and can make mistakes or write imperfect code - and that we all have a common goal, to make MK better and better. So it might be better to worry more about how to fix something that has gone wrong, and less about who caused it to go wrong. 

It is not my intention to spark debate over who did it - apologies if it seemed that way.

I have autism, which (for me) means I have a difficult time communicating, vocabularies are sometimes difficult and I often use words or entire sentence structures interchangeably. I did not intend to pin the issue on any individual, just a mistake of wording on my part.

Again, apologies to everyone, and thank you for pointing out my mistake.

**Comment by jpirnay** [comment]
I can assure you, no harm was detected or felt. We are happy to have you around

**Comment by Sophist-UK** [comment]
> > I cannot believe that it is me saying this, but let's try to remember that we are all of us human and can make mistakes or write imperfect code - and that we all have a common goal, to make MK better and better. So it might be better to worry more about how to fix something that has gone wrong, and less about who caused it to go wrong.
> 
> It is not my intention to spark debate over who did it - apologies if it seemed that way.
> 
> I have autism, which (for me) means I have a difficult time communicating, vocabularies are sometimes difficult and I often use words or entire sentence structures interchangeably. I did not intend to pin the issue on any individual, just a mistake of wording on my part.
> 
> Again, apologies to everyone, and thank you for pointing out my mistake.

I assure everyone here that I was NOT pointing the finger of blame at any individual for blaming others themselves - I am not *that* hypocritical.
