### ISSUE TITLE
[bug] 0.9.5b8: Hiding /showing elements does not remove them from operations

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2679]
I genuinely don't know whether this is a bug or not.

Hiding some elements I was expecting them to be removed from the operations they were assigned to and was surprised when they weren't. They were still in the operation, but there wasn't a ghost symbol next to them in the Operations part of the tree so you couldn't tell that they were not going to be burned until you did a simulation. 

I guess I was expecting them to be reassigned to an operation when they were unhidden. But the problem then is that the automatic classification might assign them to a different operation when they were unhidden.

So I would think that either:

* The operation element node should also show the ghost symbol; or
* The operation element node should be hidden (but not removed) and shown again when the base element is unhidden - so the manually assigned operations for an element would not change when the element is hidden and then unhidden.

**Comment by jpirnay** [comment]
Addressed in #2682 : Reference objects will display the ghost icon too if the parent element is hidden
