### ISSUE TITLE
[Bug]: Win64 executable in assets won't connect to M2nano controller

### ISSUE THREAD

**Issue by cminssie** [meerk40t/meerk40t#2687]
### Summary Description

9.4 is connecting natively in usb without problems.
Is there something that should be changed in config grom 9.4 to 9.5 ? (Windows 64bits)

### MeerK40t Version

9.5

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by cminssie** [comment]
Hi,Yes the 32 bits release connect well.Thanks for the advise.This product is great value.
Christian Minssieux06 89 88 25 ***@***.***
316 chemin de Chaillonnette38460 Crémieu 

    Le lundi 28 octobre 2024 à 20:03:02 UTC+1, jpirnay ***@***.***> a écrit :  
 
 


The 64 bit version might still face issues - please fall back to the regular (32bit) version (meerk40t.exe) - but: please share the output being displayed in the controller window.
And please try meerk40t-win-all.exe too

**Comment by jpirnay** [comment]
Due to experimental win64 compilation - we have one instance where we can create a working win64 executable - so we still need to figure out what's different on that local machine vs the github virtual instance

**Comment by jpirnay** [comment]
Wont build win64 versions for now.
