### ISSUE TITLE
[Suggestion]: REST API

### ISSUE THREAD

**Issue by Daniel-Spirgel** [meerk40t/meerk40t#2698]
### Summary Description

Having the functionality to interact with Meerk40t via REST API would be extremely helpful. One of the downfalls of Lightburn is that they don't expose any API endpoints. We would love to build integrations between ERP/Order management software directly to Meerk40t via API. 

### MeerK40t Version

Most recent

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by Daniel-Spirgel** [comment]
@jpirnay

**Comment by jpirnay** [comment]
[api recipe.docx](https://github.com/user-attachments/files/17633511/api.recipe.docx)
