### ISSUE TITLE
[Bug]:Version  0.9.5.2 Crash on Mac at startup, only the crash and splash screen are show. 

### ISSUE THREAD

**Issue by manuel1414** [meerk40t/meerk40t#2699]
### Summary Description

![Captura de pantalla 2024-10-30 a la(s) 21 16 42](https://github.com/user-attachments/assets/faef2254-f79d-4279-ac38-91c4798a1dbc)

### Crash logs

```shell
MeerK40t crash log. Version: 0.9.5200 on Darwin: Python 3.8.7: x86_64 - wxPython: 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1
Traceback (most recent call last):
  File "mk40t.py", line 11, in <module>
  File "meerk40t/main.py", line 198, in run
  File "meerk40t/main.py", line 230, in _exe
  File "meerk40t/kernel/kernel.py", line 1150, in __call__
  File "meerk40t/kernel/kernel.py", line 860, in set_kernel_lifecycle
  File "meerk40t/gui/plugin.py", line 410, in plugin
  File "meerk40t/kernel/kernel.py", line 2296, in console
  File "meerk40t/kernel/kernel.py", line 2342, in _console_parse
  File "meerk40t/kernel/functions.py", line 286, in inner
  File "meerk40t/gui/wxmeerk40t.py", line 710, in window_open
  File "meerk40t/gui/wxmeerk40t.py", line 699, in window_open
  File "meerk40t/kernel/context.py", line 419, in open_as
  File "meerk40t/gui/wxmmain.py", line 243, in __init__
  File "meerk40t/gui/mwindow.py", line 36, in __init__
  File "meerk40t/gui/themes.py", line 192, in set_window_colors
wx._core.wxAssertionError: C++ assertion ""IsOk()"" failed at /private/var/folders/ng/qbrmmqsx6990j5cfzz6t_z0h0000gn/T/pip-install-x53_dp_9/wxpython_8de19be4eb1141a98a5a5d6b51ee1eb4/ext/wxWidgets/src/osx/core/colour.cpp(219) in OSXGetNSColor(): invalid colour


Local variables:
[mk40t.py:11, in <module>]:
__name__ : __main__
__doc__ : None
__package__ : None
__loader__ : <class '_frozen_importlib.BuiltinImporter'>
__spec__ : None
__annotations__ : {}
__builtins__ : <module 'builtins' (built-in)>
__file__ : /Applications/MeerK40t.app/Contents/MacOS/mk40t.py
sys : <module 'sys' (built-in)>
pyimod03_importers : <module 'pyimod03_importers' from 'PyInstaller/loader/pyimod03_importers.py'>
os : <module 'os' from '/Applications/MeerK40t.app/Contents/MacOS/os.pyc'>
VIRTENV : VIRTUAL_ENV
python_path : ['/Applications/MeerK40t.app/Contents/MacOS/base_library.zip', '/Applications/MeerK40t.app/Contents/MacOS/lib-dynload', '/Applications/MeerK40t.app/Contents/MacOS']
pth : /Applications/MeerK40t.app/Contents/MacOS
NullWriter : <class '__main__.NullWriter'>
encodings : <module 'encodings' from '/Applications/MeerK40t.app/Contents/MacOS/base_library.zip/encodings/__init__.pyc'>
ctypes : <module 'ctypes' from '/Applications/MeerK40t.app/Contents/MacOS/ctypes/__init__.pyc'>
LibraryLoader : <class 'ctypes.LibraryLoader'>
DEFAULT_MODE : 4
_frozen_name : <function _frozen_name at 0x107c9c4c0>
PyInstallerImportError : <class '__main__.PyInstallerImportError'>
PyInstallerCDLL : <class '__main__.PyInstallerCDLL'>
PyInstallerPyDLL : <class '__main__.PyInstallerPyDLL'>
dyld : <module 'ctypes.macholib.dyld' from '/Applications/MeerK40t.app/Contents/MacOS/ctypes/macholib/dyld.pyc'>
d : /Applications/MeerK40t.app/Contents/MacOS/eggs
re : <module 're' from '/Applications/MeerK40t.app/Contents/MacOS/base_library.zip/re.pyc'>
multiprocessing : <module 'multiprocessing' from '/Applications/MeerK40t.app/Contents/MacOS/multiprocessing/__init__.pyc'>
spawn : <module 'multiprocessing.spawn' from '/Applications/MeerK40t.app/Contents/MacOS/multiprocessing/spawn.pyc'>
_args_from_interpreter_flags : <function _args_from_interpreter_flags at 0x10804fee0>
_freeze_support : <function _freeze_support at 0x107e64ca0>
forking : <module 'multiprocessing.popen_fork' from '/Applications/MeerK40t.app/Contents/MacOS/multiprocessing/popen_fork.pyc'>
spawning : <module 'multiprocessing.popen_spawn_posix' from '/Applications/MeerK40t.app/Contents/MacOS/multiprocessing/popen_spawn_posix.pyc'>
FrozenSupportMixIn : <class '__main__.FrozenSupportMixIn'>
_Popen : <class '__main__._Popen'>
_Spawning_Popen : <class '__main__._Spawning_Popen'>
tcldir : /Applications/MeerK40t.app/Contents/MacOS/tcl
tkdir : /Applications/MeerK40t.app/Contents/MacOS/tk
is_darwin : True
pathlib : <module 'pathlib' from '/Applications/MeerK40t.app/Contents/MacOS/pathlib.pyc'>
pkg_resources : <module 'pkg_resources' from '/Applications/MeerK40t.app/Contents/MacOS/pkg_resources/__init__.pyc'>
FrozenImporter : <class 'pyimod03_importers.FrozenImporter'>
SYS_PREFIX : /Applications/MeerK40t.app/Contents/MacOS
_TocFilesystem : <class '__main__._TocFilesystem'>
_toc_tree_cache : {}
PyiFrozenProvider : <class '__main__.PyiFrozenProvider'>
atexit : <module 'atexit' (built-in)>
shutil : <module 'shutil' from '/Applications/MeerK40t.app/Contents/MacOS/shutil.pyc'>
tempfile : <module 'tempfile' from '/Applications/MeerK40t.app/Contents/MacOS/tempfile.pyc'>
configdir : /var/folders/d9/jz4fwm9s64j13tf6xx2lb3jm0000gp/T/org.tatarize.meerk40t/tmpdpnwbdym
ssl : <module 'ssl' from '/Applications/MeerK40t.app/Contents/MacOS/ssl.pyc'>
glob : <module 'glob' from '/Applications/MeerK40t.app/Contents/MacOS/glob.pyc'>
libusb10 : <module 'usb.backend.libusb1' from '/Applications/MeerK40t.app/Contents/MacOS/usb/backend/libusb1.pyc'>
libusb01 : <module 'usb.backend.libusb0' from '/Applications/MeerK40t.app/Contents/MacOS/usb/backend/libusb0.pyc'>
openusb : <module 'usb.backend.openusb' from '/Applications/MeerK40t.app/Contents/MacOS/usb/backend/openusb.pyc'>
get_load_func : <function get_load_func at 0x1085a8c10>
main : <module 'meerk40t.main' from '/Applications/MeerK40t.app/Contents/MacOS/meerk40t/main.pyc'>
[meerk40t/main.py:198, in run]:
argv : []
args : Namespace(auto=False, batch=None, console=False, disable_ansi=False, execute=None, gui_suppress=False, input=None, lock_device_config=False, lock_general_config=False, maximized=False, minimized=False, no_gui=False, no_plugins=False, nuke_settings=False, output=None, profile=None, profiler=None, quit=False, set=None, simpleui=False, verbose=False, version=False)
python_version_required : (3, 6)
[meerk40t/main.py:230, in _exe]:
restarted : False
args : Namespace(auto=False, batch=None, console=False, disable_ansi=False, execute=None, gui_suppress=False, input=None, lock_device_config=False, lock_general_config=False, maximized=False, minimized=False, no_gui=False, no_plugins=False, nuke_settings=False, output=None, profile=None, profiler=None, quit=False, set=None, simpleui=False, verbose=False, version=False)
external_plugins : <function plugin at 0x108a2d160>
internal_plugins : <function plugin at 0x108a2d0d0>
Kernel : <class 'meerk40t.kernel.kernel.Kernel'>
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5200)
auto : False
console : False
idx : 1
attrib : mktabpositions
[meerk40t/kernel/kernel.py:1150, in __call__]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5200)
partial : False
[meerk40t/kernel/kernel.py:860, in set_kernel_lifecycle]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5200)
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5200)
position : 1000
args : ()
kwargs : {}
channel : Channel('kernel-lifecycle', buffer_size=0, line_end=None)
objects : [<meerk40t.kernel.kernel.Kernel object at 0x10895fb20>]
klp : <function Kernel.kernel_lifecycle_position at 0x108aa6dc0>
start : 0
end : 1000
k : Kernel(MeerK40t, MeerK40t, 0.9.5200)
plugin : <function plugin at 0x1292bc550>
plugin_list : [<function module_plugin at 0x129470ee0>]
i : 0
domain : provider/device/ruida
module_path : module/wxMeerK40t
[meerk40t/gui/plugin.py:410, in plugin]:
lifecycle : mainloop
kernel_root : Context('/')
prompt_popup : <function plugin.<locals>.prompt_popup at 0x136b9d8b0>
yesno_popup : <function plugin.<locals>.yesno_popup at 0x136b9db80>
BusyInfo : <class 'meerk40t.gui.busy.BusyInfo'>
kargs : {}
notification_message : <function plugin.<locals>.notification_message at 0x136ba0700>
interrupt : <function plugin.<locals>.interrupt at 0x136ba0940>
flag : False
icons : <module 'meerk40t.gui.icons' from '/Applications/MeerK40t.app/Contents/MacOS/meerk40t/gui/icons.pyc'>
image : <wx._core.Bitmap object at 0x136ba0160>
APPLICATION_VERSION : 0.9.5200
system : <function system at 0x1081b5e50>
shutdown : <function plugin.<locals>.shutdown at 0x136ba0e50>
_ : <built-in function GetTranslation>
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5200)
meerk40tgui : wxMeerK40t(Context('/'), name="module/wxMeerK40t")
[meerk40t/kernel/kernel.py:2296, in console]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5200)
data : window open MeerK40t
       
data_out : None
pos : 20
command : window open MeerK40t
[meerk40t/kernel/kernel.py:2342, in _console_parse]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5200)
text : open MeerK40t
channel : Channel('console', buffer_size=0, line_end=None)
data : Context('/')
input_type : window
post : []
post_data : {}
_ : <built-in function GetTranslation>
pos : 4
remainder : MeerK40t
command : open
command_executed : False
funct : <function wxMeerK40t.sub_register.<locals>.window_open at 0x132cbcee0>
name : command/window/open
regex : open
match : re.compile('plan')
[meerk40t/kernel/functions.py:286, in inner]:
command : open
remainder : 
channel : Channel('console', buffer_size=0, line_end=None)
ik : {'_': <built-in function GetTranslation>, 'data': Context('/'), 'data_type': 'window', 'post': [], 'post_data': {}}
options : [{'type': <class 'int'>, 'help': 'Multi window flag for launching multiple copies of this window.', 'name': 'multi', 'short': 'm'}]
arguments : [{'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}]
stack : [{'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}]
kwargs : {'window': 'MeerK40t'}
argument_index : 1
opt_index : 1
pos : 8
nargs : 1
kind : PARAM
value : MeerK40t
start : 0
k : {'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}
key : window
pk : {'type': <class 'int'>, 'help': 'Multi window flag for launching multiple copies of this window.', 'name': 'multi', 'short': 'm'}
current : ['MeerK40t']
command_return_context : None
func : <function wxMeerK40t.sub_register.<locals>.window_open at 0x132cbce50>
inner : <function wxMeerK40t.sub_register.<locals>.window_open at 0x132cbcee0>
[meerk40t/gui/wxmeerk40t.py:710, in window_open]:
command : open
data : Context('/')
multi : None
kwargs : {'data_type': 'window', 'post': [], 'post_data': {}}
context : Context('/')
window_class : <class 'meerk40t.gui.wxmmain.MeerK40t'>
new_path : None
window_open : <function wxMeerK40t.sub_register.<locals>.window_open.<locals>.window_open at 0x136ba0d30>
window_close : <function wxMeerK40t.sub_register.<locals>.window_open.<locals>.window_close at 0x136ba00d0>
_ : <built-in function GetTranslation>
args : ()
channel : Channel('console', buffer_size=0, line_end=None)
parent : None
path : Context('/')
window : MeerK40t
window_name : window/MeerK40t
window_uri : window/MeerK40t
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5200)
[meerk40t/gui/wxmeerk40t.py:699, in window_open]:
a : (None,)
k : {}
_ : <built-in function GetTranslation>
args : ()
channel : Channel('console', buffer_size=0, line_end=None)
parent : None
path : Context('/')
window : MeerK40t
window_name : window/MeerK40t
window_uri : window/MeerK40t
[meerk40t/kernel/context.py:419, in open_as]:
self : Context('/')
registered_path : window/MeerK40t
instance_path : window/MeerK40t
args : (None,)
kwargs : {}
open_object : <class 'meerk40t.gui.wxmmain.MeerK40t'>
[meerk40t/gui/wxmmain.py:243, in __init__]:
self : MeerK40t(Context('/'), name="window/MeerK40t")
args : (Context('/'), 'window/MeerK40t', None)
kwds : {}
width : 1920
height : 1080
__class__ : <class 'meerk40t.gui.wxmmain.MeerK40t'>
[meerk40t/gui/mwindow.py:36, in __init__]:
self : MeerK40t(Context('/'), name="window/MeerK40t")
width : 1728
height : 972
context : Context('/')
path : window/MeerK40t
parent : None
style : 541072960
args : ()
kwds : {}
[meerk40t/gui/themes.py:192, in set_window_colors]:
self : Service('themes', None)
win : MeerK40t(Context('/'), name="window/MeerK40t")
tp : {'win_bg': None, 'win_fg': None, 'button_bg': None, 'button_fg': None, 'text_bg': None, 'text_fg': None, 'list_bg': None, 'list_fg': None, 'label_bg': None, 'label_fg': None, 'highlight': None, 'inactive_bg': None, 'inactive_fg': None, 'pause_bg': None, 'pause_fg': wx.Colour(0, 0, 0, 255), 'start_bg': None, 'start_fg': None, 'start_bg_inactive': None, 'start_fg_focus': None, 'stop_bg_inactive': None, 'stop_bg': None, 'stop_fg': None, 'stop_fg_focus': None, 'arm_bg': None, 'arm_fg': None, 'arm_bg_inactive': None, 'arm_fg_focus': None}
```

### MeerK40t Version

0.9.5.2

### MeerK40t Type

Executable

### Your Operating System

Mac (before M1/Bigsur)

**Comment by manuel1414** [comment]
Runing from source:

MeerK40t crash log. Version: 0.9.5200 src on Darwin: Python 3.12.0: x86_64 - wxPython: 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/idlelib/run.py", line 580, in runcode
    exec(code, self.locals)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t.py", line 11, in <module>
    sys.exit(main.run())
             ^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/main.py", line 198, in run
    _run = _exe(False, args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/main.py", line 230, in _exe
    kernel()
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 1150, in __call__
    self.set_kernel_lifecycle(self, LIFECYCLE_KERNEL_SHUTDOWN)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 860, in set_kernel_lifecycle
    plugin(kernel, "mainloop")
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/plugin.py", line 410, in plugin
    kernel.console("window open MeerK40t\n")
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 2296, in console
    data_out = self._console_parse(command, channel=self._console_channel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 2342, in _console_parse
    data, remainder, input_type = funct(
                                  ^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/functions.py", line 286, in inner
    returned = func(command=command, channel=channel, **ik, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmeerk40t.py", line 710, in window_open
    window_open(None)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmeerk40t.py", line 699, in window_open
    path.open_as(window_uri, window_name, parent, *args)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/context.py", line 419, in open_as
    instance = open_object(self, instance_path, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmmain.py", line 243, in __init__
    super().__init__(int(width * 0.9), int(height * 0.9), *args, **kwds)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/mwindow.py", line 36, in __init__
    self.window_context.themes.set_window_colors(self)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/themes.py", line 192, in set_window_colors
    win.SetBackgroundColour(tp["win_bg"])
wx._core.wxAssertionError: C++ assertion ""IsOk()"" failed at /Users/robind/projects/bb2/dist-osx-py312/build/ext/wxWidgets/src/osx/core/colour.cpp(219) in OSXGetNSColor(): invalid colour

**Comment by jpirnay** [comment]
It looks like you can run from source? Please fetch the latest code from GitHub and run it again, and tell me what message is given on the console. I would be grateful for your meerk40t.cfg file, too, to be able to check what's going on.
Are you running on proper Apple Hardware or on a hackintosh style system?

**Comment by jpirnay** [comment]
Duplicate to issue #2699 - will continue discussion there
In a nutshell, should be fixed

**Comment by manuel1414** [comment]
This is the log in Terminal:

iMac-de-Manuel:~ Laser$ python3 /Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t.py
OpenCV is not installed. Disabling Camera. Install with:
	pip install opencv-python-headless
MeerK40t crash log. Version: 0.9.5200 src on Darwin: Python 3.12.0: x86_64 - wxPython: 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1
Traceback (most recent call last):
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t.py", line 11, in <module>
    sys.exit(main.run())
             ^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/main.py", line 198, in run
    _run = _exe(False, args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/main.py", line 230, in _exe
    kernel()
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 1150, in __call__
    self.set_kernel_lifecycle(self, LIFECYCLE_KERNEL_SHUTDOWN)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 860, in set_kernel_lifecycle
    plugin(kernel, "mainloop")
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/plugin.py", line 410, in plugin
    kernel.console("window open MeerK40t\n")
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 2296, in console
    data_out = self._console_parse(command, channel=self._console_channel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/kernel.py", line 2342, in _console_parse
    data, remainder, input_type = funct(
                                  ^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/functions.py", line 286, in inner
    returned = func(command=command, channel=channel, **ik, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmeerk40t.py", line 710, in window_open
    window_open(None)
[MeerK40t.txt](https://github.com/user-attachments/files/17592698/MeerK40t.txt)

  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmeerk40t.py", line 699, in window_open
    path.open_as(window_uri, window_name, parent, *args)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/kernel/context.py", line 419, in open_as
    instance = open_object(self, instance_path, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/wxmmain.py", line 243, in __init__
    super().__init__(int(width * 0.9), int(height * 0.9), *args, **kwds)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/mwindow.py", line 36, in __init__
    self.window_context.themes.set_window_colors(self)
  File "/Users/Laser/Downloads/meerk40t-0.9.5200/meerk40t/gui/themes.py", line 192, in set_window_colors
    win.SetBackgroundColour(tp["win_bg"])
wx._core.wxAssertionError: C++ assertion ""IsOk()"" failed at /Users/robind/projects/bb2/dist-osx-py312/build/ext/wxWidgets/src/osx/core/colour.cpp(219) in OSXGetNSColor(): invalid colour

Abort trap: 6
iMac-de-Manuel:~ Laser$

**Comment by manuel1414** [comment]
[MeerK40t.txt](https://github.com/user-attachments/files/17592706/MeerK40t.txt)
