### ISSUE TITLE
0.9.5.3 Dark Mode - default=system, splash screen

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2729]
1. It was a surprise to get 0.9.5.3 start first time with different colours from before. I think that the Dark mode switch should not default to "System" for first run for existing users, but instead to "Light". For first time users, I guess "System" has more meaning.

2. Splash screen should IMO always be shown as Light theme - because otherwise it looks weird as a negative image.

3. Whilst we are talking splash screen, I do now get the software version number. A few very minor points:
![image](https://github.com/user-attachments/assets/e65ce772-4781-4747-9ee2-d3fea35f7d14)
   * "Start" should be "Starting", "Load" should be "Loading"
   * The "Loading" line doesn't change much - I am not sure whether this is because there are few modules being loaded or because it is not updating frequently enough - I get "main module" and "GUI". But with only two modules, I am not sure whether it is worth having (especially as I imagine that the splash screen only loads when you are loading the GUI anyway). Without this being updated, you can close the splash screen just before you display the GUI window.

**Comment by Sophist-UK** [comment]
Update - splash screen showed correctly on my (non-production) laptop, but was still cropped to only part of the image on my Surface Pro 3.

**Comment by jpirnay** [comment]
The cropped image is part of issue #2728
Everything is else is a feature request

**Comment by Sophist-UK** [comment]
I disagree with the default for existing users resulting in a sudden switch to dark mode being a feature request. It was a bad feature enhancement that causes a significant hiccup to the user experience.

**Comment by jpirnay** [comment]
So we agree to disagree

**Comment by Sophist-UK** [comment]
Splash screen works with scaling of 150% (but not 165%) as suggested in #2731. Not sure what #2728 has to do with this, though.

**Comment by jpirnay** [comment]
Addressed in 
- https://github.com/meerk40t/meerk40t/commit/14db72f5dcf54954cdd1c3d55c52b2763746e5bb
- https://github.com/meerk40t/meerk40t/commit/c27cf9eb777529a2dbcfefe6d89a5e3e36690cbd
