### ISSUE TITLE
[0.9.5.3] Bug: UI scaling issues

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2731]
Scaling of some parts of some widgets is wrong:

For example the size of the two boxes on the left side of the Position pane, and the height of the config panel input boxes:

## Office laptop
![image](https://github.com/user-attachments/assets/ce7cd490-bc4d-421a-a370-2415ce57bf2d)
![image](https://github.com/user-attachments/assets/c5601adf-1604-4ef4-af24-ba29e586a6b6)

## Production Surface 3 Pro
![image](https://github.com/user-attachments/assets/9bbdd4c3-9777-4a83-9899-e167b3288f19)
![image](https://github.com/user-attachments/assets/d6d48d78-c7c0-4145-8d69-93f6c305951a)

**Comment by Sophist-UK** [comment]
A wxPython bug or a wxWidgets bug? Is there a newer wxPython that fixes it?

**Comment by Sophist-UK** [comment]
I took a look and didn't find that much online about this bug. Has it been fixed but you are prevented by using the version that fixes it due to other constraints?

**Comment by jpirnay** [comment]
It hasn't been fixed - you can immediately "fix" it yourself if you lower your user scaling in the display preferences from 175% to 150%. I am not sure what the threshold is - I think it is 165?

**Comment by Sophist-UK** [comment]
I'll try that - I can probably live with a reduction of just under 6% in sizes of stuff.

**Comment by Sophist-UK** [comment]
I switched to 150% which is not too small and UI seems OK.
