### ISSUE TITLE
[0.9.3.5] Bug: Duplicate element which is inside of a group not done right

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2734]
Duplicating an element which is inside of a group should IMO result in a duplicate element inside the same group but instead it results in a duplicate group with the element inside it.

**Comment by jpirnay** [comment]
Please provide an example, here is mine that I can't see the issue
![copy_inside_group](https://github.com/user-attachments/assets/74bfd144-972b-4173-ae50-f0a0c4f111fe)
