### ISSUE TITLE
[Suggestion]: grblHAL gcode features

### ISSUE THREAD

**Issue by PCB-Rob** [meerk40t/meerk40t#2764]
### Summary Description

I'm using grblHAL for my Customer Laser Setup. ( grblHAL on SKR Pico.  With customer Laser Control Board )
I Use M3 AND M4 currently in my toolchain. Meerk40t allow only M3 OR M4 gcode.
M3=used to cut as gantry acceleration doesn't matter on a cut.
M4=used for Raster/Engrave operations, as grblHAL will adjust power based on gantry speed including acceleration.

I Use M7 AND M8 currently in my toolchain. Meerk40t allow only M7 OR M8 gcode.
M7 is used for my Encloser Fan
M8 is used for my Air Assist Pump
( basically two "external" operations )

Workaround for now, Connect both Fans to single output, use M3 config when cutting, config for M4 otherwise

### Current functionality

M3 or M4
M7 or M8

### Future functionality

Allow operation to select gcode, depending on user requirement
M3 (gcode Spindle CW , grblHAL Laser Mode, fixed PWM )
or
M4 (gcode Spindle CCW, grblHAL Laser Mode,  PWM based on current speed)

Allow M7 and M8 to be configured based on user needs 
( I currently turn off the Air Assist Pump at end of job, but turn off Encloser Fan after 30 second delay  )

### MeerK40t Version

v0.9.5.3 and v0.9.7 alpha 2

### MeerK40t Type

Executable

### Your Operating System

Linux

**Comment by jpirnay** [comment]
Thank you for your input, I will have a look at the M3 / M4 logic.
Re the different coolant methods you are using - you could circumvent that right now via a ConsoleOperation that sends a GRBL command and that is put in front of the required operations.

**Comment by PCB-Rob** [comment]
Thanks for the idea : )  Adding "gcode M7" as the 1st operation, turns on my encloser fan

**Comment by jpirnay** [comment]
Addressed in PR https://github.com/meerk40t/meerk40t/pull/2765
