### ISSUE TITLE
Cut ordering with 2-opt

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#3]
The cut optimization routine would benefit from a 2-opt correction for the travelling salesman problem to minimum the cut distances overall. This should be done with and without speed changes.

**Comment by tatarize** [comment]
This exists

**Comment by Sophist-UK** [comment]
2-opt is perhaps fast enough now to have it on by default.

**Comment by tatarize** [comment]
Hm. The speed seemed on par at times with the other ordering. Cut ordering with 2-opt exists and I wanted to get under 100 issues. So this got closed. Planning on looking through the rest of the issues for any that were generally finished.

**Comment by Sophist-UK** [comment]
Yes - we could do with a 0.7.5 proper as a final 0.7.x (maybe).
