### ISSUE TITLE
Defining Operations by Color, how many allowed? Can they be saved?

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#303]
Trying to build a complex object that will involve engraving at a variety of Power levels and speeds, so the question is:

How many Operations Colors can you have?  Any suggestions on keeping them apart?

How can you SAVE the definitions of the operations between runs?  Ie, if you set a particular Engrave speed and power, how do you save it for the next day's run?

RECOMMEND an optional NOTE for each Operations definition for FRONT PANEL POWER, again for running the same thing sometime later without having to re-discover the settings that worked.

**Comment by tatarize** [comment]
You can have any number of colors. But, only like 8 different ones are natively able to be overtly set in path properties. There's 16,777,216 permitted colors so there's 16,777,216 ways to uniquely define an operation. 

You can save a blank file between runs of the operations. This will also save the note. So when you set the note and save. That svg will also launch the note about those properties. 

This is basically what there is, it's just very non-obvious that the svgs work like this.
