### ISSUE TITLE
Problem with curves in 0.6.15

### ISSUE THREAD

**Issue by rafaljot** [meerk40t/meerk40t#307]
As long as I was cutting the squares, everything worked in 0.6.15.
An error occurred while cutting curves . 

After downgrade to 0.6.14 everything works perfect again.

Unfortunately I didn't grab stack trace nor the screenshot. Something with "floor" but I have problematic file.
Is there any log file ?

[hot bed_2.svg.zip](https://github.com/meerk40t/meerk40t/files/5851723/hot.bed_2.svg.zip)

**Comment by tatarize** [comment]
Yeah, nuking the version going to 0.6.16 shortly.

**Comment by tatarize** [comment]
The error log will save in your working directory as a text file.

**Comment by tatarize** [comment]
0.6.16 corrects this issue.
