### ISSUE TITLE
Dark Theme , OSX

### ISSUE THREAD

**Issue by rafaljot** [meerk40t/meerk40t#308]
Dark Thame is nice but there are some minor color issues:

1. Black on dark grey
2. White on yellow
3. White on light green

<img width="585" alt="Zrzut ekranu 2021-01-21 o 21 12 55" src="https://user-images.githubusercontent.com/13086437/105407302-d4e51a00-5c2d-11eb-9ca5-2c573cbc1028.png">

![image](https://user-images.githubusercontent.com/13086437/105406843-44a6d500-5c2d-11eb-8df2-732b8ff78f68.png)

<img width="511" alt="Zrzut ekranu 2021-01-21 o 21 13 10" src="https://user-images.githubusercontent.com/13086437/105407084-92bbd880-5c2d-11eb-9a43-a33254432602.png">

![image](https://user-images.githubusercontent.com/13086437/105407517-1b3a7900-5c2e-11eb-93a1-74dbdc1806fb.png)

**Comment by tatarize** [comment]
For the icons. I am pretty sure I could flip their color schemes and invert them in places. But, I don't really know when dark mode is on or not. I might be able to set them to the same color as the text depending on dark mode works. The best correction for the console color issues might be to not use angry fruit salad colors to begin with. Maybe colors that are more neutral between light and dark but still sort of reflect the current state of that thing?

**Comment by tatarize** [comment]
That icon thing in device manager is just a bug. Those are *supposed* to be up and down icons that are disabled, but apparently they just move the corner and overlap for unknown reasons. I don't really allow reordering there. But, rather than disable they get drawn weird.

**Comment by tatarize** [comment]
Frog figured out: wx.SystemSettings().GetColour(wx.SYS_COLOUR_WINDOW)

Totally gives whether dark mode is on. So some specific things could be changed based on whether dark mode exists or not.

**Comment by tatarize** [comment]
https://dzone.com/articles/wxpython-creating-dark-mode

Dunno, but it might be possible to set the background color for various windows and get it to work. Some particular widgets might not work.

----

Like two of the images you posted are just bugs. If there's something design wise, that should be shifted I'll need specifics. Gui design is not my forte.

**Comment by tatarize** [comment]
I fixed the couple bugs but I'm not a gui design person so the remaining bad darktheme stuff isn't very apparent what's required there.

**Comment by tatarize** [comment]
@rafaljot -- These may actually be fixed. I hacked the icons to invert, and I force set the color to black in the cases where I have a giant colored buttoned. Removed those two clearish bugs and should be in the beta https://github.com/meerk40t/meerk40t/releases/tag/0.6.18-beta1 I'll ping @joerlane about pumping out a beta OSX version.

**Comment by RuKeBo** [comment]
Can you access Dark mode in Windows? I can't find a setting for it.

**Comment by tatarize** [comment]
No. No dark mode in Windows. There's some idea one could be hacked in there. Just run some code on each window on start to recolor such things but currently none of that. It's an OSX thing apparently.

**Comment by tatarize** [comment]
@rafaljot Please verify 0.6.18 corrects these issues for you. Frogmaster should have also performed some additional tweaks that should work for Dark Mode.
