### ISSUE TITLE
Need Cancel button. Soft-Abort.

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#325]
There is currently no way to STOP a process without having to go through the re-zero, re-home and likely re-perspective.

Need a clean & recoverable  STOP button.

the last time I aborted a job I had to power-cycle the K40, load up K40Whisperer, "initialize laser" close K40W and THEN a load up Meerk40T as MeerK40T can't do a full "reinitialization" when it has gotten confused.

currently I will just disable the laser, and let it continue on rather than have to re-do everything after an abort....

PS....6.17 seems MUCH a better...

**Comment by tatarize** [comment]
A recoverable stop button. Like empty the current buffer, and then exist where you actually are without needing to kill things? Like nothing's in danger, go ahead and do that extra 2 seconds of data in the buffer, then just keep working without interruption. Like not "stop" but rather cancel.

**Comment by inspectionsbybob** [comment]
Cancel would work.  It is for when the material isn't placed correctly, the power is set wrong, or something else that makes you want to cancel, re-position and re-start.  Currently, a "restart" is a rather painful process involving the "other" software to re-initialize the K40...

A STOP, clear the buffer, goto PHYSICAL HOME, then to MeerK40T Home, then BEEP would be ideal.

The Goto Physical Home (0,0) establishes where you are, going to MeerK40T Home is ready to re-start work, and BEEP is READY to go.

**Comment by inspectionsbybob** [comment]
Another idea, based on the Spooler and Operations menu would be a "SKIP Current Operation".  
I was working on a "4 Up" when I realized the material wasn't secured and the air-assist had moved it.  I just wanted to SKIP the 1st of the 4 items it was going to engrave after a pause to secure everything.  The FIRST of the 4 was trashed, but the next 3 would be fine...  PAUSE, SKIP, Un-PAUSE would go to the next item after clearing out the buffer and establishing where it was.  (Home 0,0, MeerK40T Home, then on to next item) 

This would be a MAJOR feature upgrade, but very useful

**Comment by tatarize** [comment]
I think you need to hit stop a few more times and home a few more times. I've never needed to disconnect and reconnect the K40 for that. But, there's a button for that controller.

**Comment by inspectionsbybob** [comment]
My K40 Doesn't have a stop button.  Not sure if it was an earlier model or
what.  I have the ANALOG version, with a current meter, power dial, Laser
enable, and laser test.  Thats it.

The Only STOP/PAUSE button I have is the Meerk40T "PAUSE"  or the
"Controller STOP"


Please don't wait for me to respond when booking an inspection. I turn off
my devices when on appointments and someone else could get your spot.
Please CALL our service or book yourself online to save the spot as soon as
you know the time you want.

Bob Sisson ACI, BVI
Inspections by Bob
ASHI Member # 212016
MD Home inspectors License #29666*
*MAC-ASHI Chapter President 2010-2012
ASHI Mid-Atlantic Group Leader 2009-2012
ASHI National Board Of Directors 2012-2015, 2017,2018-2020
Bob@Inspectionsbybob.com
www.inspectionsbybob.com
(301) 208-8289 Scheduling/Pricing

**Comment by tatarize** [comment]
You could also try hitting the disconnect reconnect button in controller that somehow stops. I dunno why it would take resetting that elsewhere. But, resetting is part of disconnect for the program.

**Comment by inspectionsbybob** [comment]
Whenever something is "running,"  there needs to be a big red "CANCEL"
button that stays on top.  If I see a pattern will not fit on my material,
I really don't want to take the time to go looking for a menu, especially
if that menu is minimized/hidden for some reason and doesn't want to be
seen.  It needs to be K.I.S.S. (Keep it stupid simple ) simple for those of
us who want to engrave things, not necessarily play with the software. My
wife wants KISS.  If something is going wrong, she is just going to turn
off the Laser and yell, "BOB, come fix this thing..."
I need HER to run it without me and deal with MOST issues that come up
without having to re-do any calibrations or worry about what order to do
things...  It needs just to work, each time, every time, and if it doesn't
there needs to be a clear "RESET/Home/Clear/whatever..." to get it back to
a known state so SHE can run something through...



Please don't wait for me to respond when booking an inspection. I turn off
my devices when on appointments, and someone else could get your spot.
Please CALL our service or book yourself online to save the spot as soon as
you know the time you want.

Bob Sisson ACI, BVI
Inspections by Bob
ASHI Member # 212016
MD Home inspectors License #29666*
*MAC-ASHI Chapter President 2010-2012
ASHI Mid-Atlantic Group Leader 2009-2012
ASHI National Board Of Directors 2012-2015, 2017,2018-2020
Bob@Inspectionsbybob.com
www.inspectionsbybob.com
(301) 208-8289 Scheduling/Pricing

**Comment by Sophist-UK** [comment]
As above Abort on my K40 m2 nano does NOT require reinitialisation, but (as reported elsewhere) it now goes elsewhere and grinds the steppers rather than instantly stopping. Also mostly needs 2x click on Home to do an actual Home suggesting m2 nano is not left in a correct state.

But what is for sure is that when you use Abort, an unknown number of instructions already sent to the laser will be lost, and so position will be unknown. A Cancel feature that simply stops sending any more instructions should (in theory) leave a known position allowing some sort of restart as requested by @inspectionsbybob. I guess you would need to return the m2 nano to a set state - so strictly speaking some further instructions would need to be sent.
