### ISSUE TITLE
Time Estimate

### ISSUE THREAD

**Issue by kshenneman** [meerk40t/meerk40t#342]
Would it be possible to display a time estimate of the length of time it will take to complete the engraving job?

**Comment by tatarize** [comment]
There is one. It's just not helpful or very visible or right. In spooler there's a spot for time estimate. The spooler loads the first item which is often most of the work so you can't see it on that one. But, the other ones it has a bunch of wildly wrong estimates for how long it should take. 0.7.0 has some spots to make time estimation a bit more of a thing, but they also currently don't do anything.

Part of the issue with good time estimation is actually timing things.  And I'm not really sure how long things take. But, bad estimates trump no estimates.
