### ISSUE TITLE
Convert to Raster Crashes

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#349]
Clicking on some text and trying to convert to Raster I get....
![IMG_6670 1](https://user-images.githubusercontent.com/22258531/107297903-4f8da200-6a42-11eb-8ad5-ecdcfb1d3fd1.JPG)

The text of the error is:
MeerK40t crash log. Version: 0.6.18
Please report to: https://github.com/meerk40t/meerk40t/issues

Traceback (most recent call last):
  File "wxMeerK40t.py", line 2840, in specific
NotImplementedError

**Comment by tatarize** [comment]
Hm. That's convert text to vector, it doesn't exist. I'm not sure why that button wasn't removed. The bug is it's not a thing that actually exists.

**Comment by tatarize** [comment]
Also, not sure why it says Convert to Raster.  --- I guess it doesn't matter it doesn't actually do anything anyway. But, you can raster text fine, you just can't vectorize it.
