### ISSUE TITLE
Save AS error

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#350]
Had made major edits and wanted to Save AS a

and got...

MeerK40t crash log. Version: 0.6.18
Please report to: https://github.com/meerk40t/meerk40t/issues

Traceback (most recent call last):
  File "wxMeerK40t.py", line 1379, in on_click_save_as
  File "Kernel.py", line 2259, in save
  File "Kernel.py", line 1374, in save
  File "DefaultModules.py", line 80, in save
AttributeError: 'NoneType' object has no attribute 'items'

I had been making lots of moves and edits.
There were some stray "fragments" that got deleted... thinking it was one of those...

Just tried SAVE, it does the same thing.... so much for 10min of edits... again...

**Comment by tatarize** [comment]
Hm. The text in question doesn't have a values how odd. But, if you created it with console: `text this is some text` then maybe `scale 50` so you can see it. Then it might not have that. Yeah, seems like a solid bug.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.6.19-beta1
