### ISSUE TITLE
Multiple Cameras does nothing, sort of

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#370]
I had the chance to get a second camera on my K40.  I figured I would have one that would do layout from the lid by the handle where it is repeatable, and that ONE is working very well now, and one could watch from a different viewpoint when a job was running and the lid is closed.

I can't have TWO cameras running from inside MK. I have to swap back and forth, and the second camera gets the same configuration as the first, perspective and fisheye?  I was hoping to have two cameras running, each with their own viewpoint and values, and have BOTH running.  MK does not like that, and it takes some time for it to switch between cameras and "sync."

The work around, in Windows, is to use the Camera App to support the second camera. The downside is every time I click on something in MK it hides the camera app.  I have no idea what it might do with even more cameras...

**Comment by joerlane** [comment]
This is one of the notable features in the upcoming 0.7.0 version; multi-camera support.
