### ISSUE TITLE
0.7.0 beta 11 selected path in operations tree not highlighted in scene

### ISSUE THREAD

**Issue by kgwatson** [meerk40t/meerk40t#382]

**Comment by tatarize** [comment]
Confirmed. I vaguely remember Joe telling me that but I was getting a lot of bugs fixed at the time and neglected correcting that. It shouldn't be too hard to correct.

**Comment by tatarize** [comment]
Well, I did it for the selected path highlighting in scene. But, not right off for selecting the operation should select all the children within that operation that I assume is also desired. https://github.com/meerk40t/meerk40t/commit/bcd73d7a098503d2feb7b79a42ec9553e7ce4612

**Comment by tatarize** [comment]
I'll publish beta 12 with the rotary fixes and that selection fix after I get through these crash logs.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.7.0-beta12
