### ISSUE TITLE
Items merged between raster operations when saving and reloading project.

### ISSUE THREAD

**Issue by fr-og** [meerk40t/meerk40t#389]
Items are merged between raster operations upon saving and reloading a project.

Tested in versions 0.6.20, 0.6.21 & 0.7.0 beta 12

See image for example. On the left is configuration before saving, on the right is configuration after save and reloading.

![meerk40trasterissue](https://user-images.githubusercontent.com/57437116/110918773-6fe79f80-8313-11eb-990f-ecf65875b69e.jpg)

**Comment by tatarize** [comment]
#209 Yeah, they reclassify wrong or rather don't save the very specific classification data. I'll fix this likely in 0.7.0 sometime fairly soon.  Saving and loading  of somethings is still an outstanding issue there and referencing the data more correctly for many files is going to be strongly preferred.

**Comment by tatarize** [comment]
This is corrected in 0.8.x since it saves the references and restores them correctly.
