### ISSUE TITLE
STL to Depth Map

### ISSUE THREAD

**Issue by interceptor70** [meerk40t/meerk40t#392]
can you integrate an STL Tool to Depth Map

**Comment by tatarize** [comment]
https://www.youtube.com/watch?v=U0VlUeljRMI

There's a lot to that. I'm not sure there's any good stl file elements that would make much sense in python. And while the files might not be complex the conversion between the 3d and 2d stuff into a depth map very well might be really kinda hard.

While clearly cutting a depth map into different thresholded images and rastering them such that you can get the depth even with a M2 Nano is entirely within the sphere of MeerK40t I'm not sure there's easy ways to make this easy in MeerK40t even if the major parts of the code were done in a plugin.
