### ISSUE TITLE
Warn about closing app during burn

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#393]
I am truly an idiot - once is a mistake, twice is stupidity. Twice now I went to close the spooler window and instead closed the main window.

Can we please have an "Are you sure?" confirmation if we are closing Meerk40t whilst a burn is in progress?

**Comment by tatarize** [comment]
There used to be such a setting, but it got lost in one of the updates/conversions. It also has to go kinda out of the way to kill a process in progress. Otherwise the GUI closes down but the thread stays there sending data without fully killing the processes. I'll be sure to add it back.

**Comment by tatarize** [comment]
This is in the 0.6.23 branch.

**Comment by tatarize** [comment]
Published.

https://github.com/meerk40t/meerk40t/releases/tag/0.6.23
