### ISSUE TITLE
cuts everything twice?

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#398]
6.22
first try with this version
cuts all my items twice, once clockwise, the second time counter clockwise. I didn't put in any extra anything...

very weird...

Camera and USB aim general are more stable though...

**Comment by tatarize** [comment]
There's no grounds to cut counter clockwise or any different than you actually cut. The SVG has two overlapping lines. Mark my words.

**Comment by inspectionsbybob** [comment]
closed as a one-of user error
