### ISSUE TITLE
Dxf support option

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#41]
Support Dxf files.

https://en.wikipedia.org/wiki/AutoCAD_DXF

**Comment by tatarize** [comment]
https://github.com/mozman/ezdxf is a solid project MIT licensed that does the DXF work. This should work well for our ends.

**Comment by tatarize** [comment]
https://ezdxf.mozman.at

**Comment by Haleybelinda** [comment]
Any chance of bitmap also, please? (GSW)

**Comment by tatarize** [comment]
Bitmaps would be .bmp and are covered as a graphics format. You can already drag and drop them into meerk40t.

**Comment by Haleybelinda** [comment]
That is brill. Gsw is a form of bitmap from a programme I use.  It was not displaying as a valid file type. I will try drag and drop. Forgive my ignorance, where do I put the laser reference to get my machine to talk to the meerk40t?

**Comment by tatarize** [comment]
I dunno if it's compatible with standard .bmp. If it is a valid recognized image format it should be but GSW isn't any format I can find any references to so it actually seems doubtful.

**Comment by Haleybelinda** [comment]
Hi,
Thank you for getting back to me, where do I put the device I'd. To get
your programme to communicate with my laser. I have an m2 board so it
should work, I would like to try it. The software GSW uses either for
photos.
Thanks
Haley

**Comment by tatarize** [comment]
I'd save it to one of the more common graphics formats, like jpeg or png and just use it that way. The laser communicates through libusb. If whisperer works, then this would work. But, I don't really understand the problem or the question. There are instructions for getting it to work in the readme as well as some premade binaries for windows in releases.

**Comment by Haleybelinda** [comment]
Hi tatarize,
I am still using laserdraw,
I seem to have the program open it just cant find the usb. The libusbo is there. I think I need to tell the program which USB its at and cannot tell which is which. Any way thank you for your help.
Haley
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tatarize** [comment]
Yeah, you'll have to switch out your driver. Which means currently I don't have an install to do that. I'd daresay your easiest bet is to install K40Whisperer and install the driver. With the install. My setup uses the same driver methodology.

https://www.scorchworks.com/K40whisperer/k40whisperer.html so if Whisperer works so will meerk40t.

**Comment by Haleybelinda** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tatarize** [comment]
0.5.2 has most of this included. It still has some bugs but exists as a thing. @joerlane You said you found some attribute errors, can you send me some specific files to trigger those?
