### ISSUE TITLE
Meerk40t 0.6.22: Closed paths do not meet correctly

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#412]
I have noticed that closed paths do not finish at exactly the same point.

Regardless of whether they burn in a clockwise or anti-clockwise direction, the end point is always slightly closer inwards than the start point.

I noticed that there was a problem with e.g. cutting leather holes at (say) 2mm diameter, with a small piece of leather not cut through, but the reason was too small to see. However I have now seen this at large scale (pieces of several inches diameter) and the tangential difference is noticeable to the naked eye - perhaps 0.5mm (a guess - too small to measure).

I have some photos if needed - but they show only the symptoms (as described above) and do not identify the cause.

**Comment by tatarize** [comment]
There's a couple hardware problems that can do this. @joerlane might have some better info on those. I'm pretty sure it's not software related since a bug that large would stick out like a sore thumb. In theory losing some steps in the y-axis because of something to do with the belts could do such things.

**Comment by Sophist-UK** [comment]
I don't think this is a belt problem - A) because my belts are correctly tensioned (once I worked out how to do it) and B) because belts issues are usually a bit random and this is consistently happening.

Of course it could be a different hardware issue - any idea how to determine whether it is or isn't?

(And it is NOT losing steps in the Y-axis, because the large scale examples I have were out in the X-axis.)

However, if you think it would help diagnose the issue, I could do some experiments with doing multiple circles in one path and see if the errors accumulate? And try different speeds and try seeing if the orientation of the circles makes a difference e.g. whether the joining point tangent is X or Y or diagonal.

If I was to guess at the cause, I would say rounding errors accumulating over the multiple times it has to decide which of the 1000x1000 pels per square inch to move to when the path doesn't go through the exact centres of these squares and sometimes goes through a joining side or corners - and over the tens of thousands of such decisions in e.g. a 3" circle, any bias might well add up to (say) a 0.5 mm difference of position.

**Comment by tatarize** [comment]
You could try rotating the shape by 90°, in theory a hardware error would cause either an overlap or gap at the return point. But, a software error might make the same shape. 

The guess is pretty good, but I ran into that type of bug in embroidery a bunch and I account for it. 

```python
     x = self.context.current_x
     y = self.context.current_y
...
     dx = x - self.context.current_x
     dy = y - self.context.current_y
...
     dx = int(round(dx))
     dy = int(round(dy))
...
     self.context.current_x += dx
     self.context.current_y += dy
```

x and y are the current location, dx is solved as the distance between the last position and current position. dx and dy are then made integer values. Those int values are then subtracted/added back out. This means any fractional amount of position is correctly accounted.

If you move 1mm (393.701) on the laser, you and look at the data sent to the laser, is sometimes 394 and sometimes 393, depending on the fractional error at particular times. I tend to account for that error type in most of my projects.

**Comment by Sophist-UK** [comment]
Your algorithm looks correct - maintaining an accurate position based on actual moves and calculating the next delta based on that not the previous non-rounded position.

Since this is Python, all the variables are not a fixed type. What level of precision is self.context.current_*? (And what is the measurement type? mm?)

**Comment by joerlane** [comment]
I would repeat tatarize's suggestion to rotate the object in question by 90 degrees. I have indeed seen this issue, and it was in fact related to hardware. The X and Y axis have different modes of failure; that may or may not be related to the belt tension explicitly. I don't know of any software issues that could cause this problem. 

I actually use a simple test file based on this problem to ensure my hardware is properly adjusted.

**Comment by tatarize** [comment]
I might also suggest using whisperer to draw the same shape. If it does it in Whisperer it's guaranteed hardware.

**Comment by Sophist-UK** [comment]
I can try that too as soon as I have time. Too busy preparing for a craft fair on Sunday at present.

**Comment by Sophist-UK** [comment]
I found that I had not found all the belts and the hidden one on the right is loose, and I cannot manage to tighten it through the hole in the back so it will have to wait until I take the gantry out from the case and adjust it and then re-allign the lasers.

**Comment by joerlane** [comment]
Another thing to watch out for; sometimes the belt can be correctly tensioned, but afterward the pulley flops around. They aren't mounted very securely. Sometimes I have to jiggle that on the front side while adjusting again to make it work.

I use a regular length phillips head screwdriver through the round hole in the back of the case. It takes a good bit of searching to find it (quite frustrating at times). Luckily it's not something that's required very often. 

Unless you meant the X belt; and that adjusts through the round hole by the power supply. Just pull the gantry to the middle.

**Comment by Sophist-UK** [comment]
There are two holes in the back below the laser for the left and right Y-belts. I tensioned the left hand one (and the X-belt) but not the right hand one when the K40 first arrived, but when I tried a screwdriver today, I could find the screw head, but the hole in the back was off centre and I couldn't get the screwdriver to engage enough to turn the screw. So I will need to take the gantry out and see what is happening and why it won't adjust.

**Comment by Sophist-UK** [comment]
I don't think this is an issue with a loose Y-belt because the issue appears on the X-axis. X-belt seems tight enough.

However when I draw 3 large circles right to left, the laser cuts the first one perfectly and the next two incorrectly. Which suggests that the head is moving not quite far enough when it moves from circle to circle, suggesting that it is an issue with the X-belt. I will have to look into this when I take the gantry out.

**Comment by joerlane** [comment]
I've never had to take the gantry out; that's a whole different can of worm that might cause other issue depending on how well the specific machine was built in the first place.

Another thing to consider; if it's not explicitly the belt tension. The rollers on the head may not be hugging to the gantry well enough (which can cause slop upon direction change), assuming it's really an X issue.  Each wheel is adjustable individually. 

Obviously hard to say without being able to poke at the machine in real life.

**Comment by Sophist-UK** [comment]
I have already taken the gantry out a couple of times when modifying the stock air duct - it really is not difficult (from memory 4 bolts and nuts), but when you put it back it won't be in **exactly** the same position (to the mil) as it was before - so you have to tweak the laser alignment.

I have tried moving the head in the X direction by hand with the steppers locked - and there is not any significant amount of play in  the X-direction. And the belts have a twang when you pluck them. But I will check the wheels.
