### ISSUE TITLE
Spooler: Can we have an ability to insert a beep?

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#423]
It would be great to have an ability to insert a beep before an operation in the spooler.

I can also potentially see a need to insert a Home if the K40 has lost position for any reason.

**Comment by tatarize** [comment]
This doesn't come up often enough to get a gui. Though there is a standing issue that you should be able to reorganize that stuff in the gui and put the bits where you need. But, without that: the console command to insert a beep at say position 3 would be: `plan command -o beep -i 3`

Keep in mind this works with the current plan, so it would put that command in before or after it converts to cutcode during the blob.
