### ISSUE TITLE
Arrange RibbonBar in more robust fashion. Should have an method to madness.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#432]
![new window](https://user-images.githubusercontent.com/3302478/119342110-71a1dd80-bc49-11eb-8e3c-9ed4b3172182.png)

Currently I think maybe Controller and Preferences should be renamed and tasked. Preferences are specifically the Driver Preferences of the current device and Controller monitors the Output of the current Device.

**Comment by Sophist-UK** [comment]
Better - but I would suggest:
* Start Job -> Execute Job
* Compile and Simulate -> Simulate
* Controller I am fine with.
* Preferences -> Configuration
* Settings -> Preferences
* Group: Main -> Project
* Group: Window -> Control
* Move Console to the end of Main group.
* Move Pause (/Resume) to the right of Spooler - or with the big Stop / Home buttons at the bottom (not showing in the pic above)
* Settings and Preferences should have different icons.
* Usb button - see previous discussion about debug - don't you get the same info in an optional panel of the controller window? Can we dispense with this?

**Comment by tatarize** [comment]
![version2-gui](https://user-images.githubusercontent.com/3302478/119348523-d5300900-bc51-11eb-91a7-2ed793c5deff.png)

Fetching a new icon took the most time. Though I did find a nice ram chip icon. Not sure what it'll be used for but it's clearly perfect for something.

**Comment by tatarize** [comment]
Also, of interest. This is a lot of real estate for 17 buttons.

**Comment by tatarize** [comment]
![version3-gui](https://user-images.githubusercontent.com/3302478/119350193-e1b56100-bc53-11eb-8648-8361c0d4a29c.png)

I lean towards this a bit. Mostly because Devices are a real thing now. And they basically setup the Spooler, Config, and Controller. And Pause looked dumb left in windows. Maybe Navigator would want to move too leaving camera all alone in Window.

**Comment by Sophist-UK** [comment]
I still think pause is like the emergency cancel or home panels. And Devices and Config definitely belong in Settings. And Spooler and Controller seem to fit with Navigation and Camera into a set of laser controls.

So I preferred the previous design plus my changes to this.

**Comment by Sophist-UK** [comment]
My thinking is more about what buttons get used when i.e. user centric.

**Comment by tatarize** [comment]
![gui4](https://user-images.githubusercontent.com/3302478/119371117-ee917f00-bc6a-11eb-9d58-0ad5ab7dff9b.png)

Well I couldn't get the ribbon bar to minimize but I made the little arrow there let you get the taskbar thing for it and consequently close it. I added a couple panes like navigation for show. These could be disabled or put where-ever, though highly customizable some consideration needs to be given towards initial arrangements.

**Comment by tatarize** [comment]
https://user-images.githubusercontent.com/3302478/119372953-c014a380-bc6c-11eb-8370-198b0b092cd1.mp4

**Comment by tatarize** [comment]
The problem I have is that config and controller change in other devices. They might even be absent. That's because classwise those really are devices.

We could throw away pause and do that in a pane if folks wanted such a thing. It's a pretty easy change. In fact, done.

**Comment by Sophist-UK** [comment]
I quite like the idea that you can move the buttonbar anywhere or close it - can we have that as standard?

And I see we now have View/Panes/stuff which is great.

So dispense with the up/down arrow, and if possible move the help button to the end of the menu bar - or if not add a Help menu which has a variety of places to go for help.

**Comment by tatarize** [comment]
![gui5](https://user-images.githubusercontent.com/3302478/119374115-0cacae80-bc6e-11eb-8bd4-29eb55d4ae29.png)

**Comment by Sophist-UK** [comment]
I like that more than a button on the button bar. Does it switch to a resume icon when you click it?

If Config and Controller change with the device, (understandable) and if the other device doesn't have these, then we simply grey out the buttons or remove them.

**Comment by tatarize** [comment]
Help is a on the menu bar, language goes last because it's added dynamically if there are translations. But, help is always there and launches the wiki stuff etc. 

It didn't... but now it does.

Doesn't update though if something else changes it.

**Comment by tatarize** [comment]
Currently the buttons launch a weird thing that says there's no gui for this thing. But, others like File or TCP might well be better off with a different icon and name. Or a different button that is turned on and the other turned off as needed.

**Comment by tatarize** [comment]
https://user-images.githubusercontent.com/3302478/119376254-965d7b80-bc70-11eb-83c0-f53efbfd06db.mp4

**Comment by tatarize** [comment]
I'll get to whatever ideas you have in due course, heading to bed. I'm pretty close to having optimization working. I need a few more tweaks but the simulation is generally kinda reasonable. I did set passes to 3 and it went a bit crazy. But, that might be a side-effect bug. And the rotary scaling effects the main scene, and a couple more known bugs. But, it's almost to big old bug-hunt time.
