### ISSUE TITLE
Perspective Dots Hide Targets

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#437]
Playing a bit with 0.7 Beta...
The Perspective Alignment "dots" hide the Targets so you cant precisely align the frame
Would prefer "crosshairs" or something like that...
The dot bellow and to the left is the mark I am trying to align on...
![IMG_7250](https://user-images.githubusercontent.com/22258531/120050043-fabe6900-bfe9-11eb-8090-ffed07b9f849.JPG)
I tried to align as best as I could.... I was off quite a bit...

![IMG_7249](https://user-images.githubusercontent.com/22258531/120050116-33f6d900-bfea-11eb-940b-e0d74e85432f.JPG)

**Comment by tatarize** [comment]
Fixed in RC2
