### ISSUE TITLE
What Happened to Fisheye Correction Msgs

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#438]
Trying to align my system with 0.70...

Went to Fisheye.... clicked on the Eye to scan for the Grid.... NOTHING...
No Message of success or Failure or "can't find Grid"
Nothing....

**Comment by tatarize** [comment]
Fixed in RC3. Wasn't there at the actual cutoff but, I moved it forward so you wouldn't need to wait the whole day.
