### ISSUE TITLE
Raster alignment is off and tree plane becomes weird.

### ISSUE THREAD

**Issue by bergie5737** [meerk40t/meerk40t#445]
Hi.
I have a few puzzles to laser cut and decided to see how this fair compared to K40Whisperer. I'm impressed with the software and sure it is better! Thanks for the hard work. One issue I found, is where I make a small name puzzle, the text is not inside the puzzle anymore. See screenshot.

![image](https://user-images.githubusercontent.com/10572409/121186191-fa558600-c8a5-11eb-8b87-d9d58dffae1e.png)

I tried to enlarge the "tree" pane, to show the font detail, but then the screen becomes weird, See below.
![image](https://user-images.githubusercontent.com/10572409/121186933-b2832e80-c8a6-11eb-8135-9daa043ad91f.png)

Hope it helps. I am trying v0.7.0 RC6 on Windows 10.

**Comment by Sophist-UK** [comment]
You need to convert the text to paths inside Inkscape to make this work.

**Comment by tatarize** [comment]
The text there is dynamic. The idea was to do the harder thing and keep it editable so you could do things like make flowable text or a series of monogrammed basesballs or something. And not need to make a different svg file for each. The arranging of the text, however, is a bit hard and is off. Text2Path would bypass this and just make the text a normal shape. It's a clear defect in the program currently and methods of fixing this, thus far have been a bit lackluster.

**Comment by Abizarl** [comment]
Love what is being done with the software. Have the same issue as bergie5737. Text (rasters) are off but also having an issue with imports of non-raster data. Have not tried the text to paths yet for the raster data
![MeerK40 and Whisperer](https://user-images.githubusercontent.com/39865731/128774013-c4612c99-caa1-45d8-a921-be550f5e8573.jpg)
. The attached image shows a few files after import into Whisperer and into MeerK40t.

**Comment by Sophist-UK** [comment]
As I said before, currently you need to convert the text to paths inside Inkscape to make this work.

**Comment by Abizarl** [comment]
Thanks for the quick response!

**Comment by Sophist-UK** [comment]
Closing.
