### ISSUE TITLE
Trying add "Home" adds "300" instead

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#454]
I went to add a "Home" after my last operation and the event it added was 

"300"

exited, reloaded and it did the same thing...

was trying to run a simple job, but a job, so I couldn't verify the other specials such as "Beep"

**Comment by tatarize** [comment]
Hm. Weird fluke. It's the number for the command in the lasercode. Not sure why it's not plaintext.

**Comment by Sophist-UK** [comment]
Which version of MK?

**Comment by tatarize** [comment]
RC-7. Yeah, it does it. I changed some of the naming stuff so it went to a default name for it, which is not the .name but 300 which is the value of the `Special Command`

**Comment by inspectionsbybob** [comment]
I was able to confirm ALL of the operations come over as numbers on the operations Tree,  
![error](https://user-images.githubusercontent.com/22258531/126041422-5e006d84-6087-419f-adf6-8976e865f210.jpg)

**Comment by tatarize** [comment]
This is now fixed in RC8.

https://github.com/meerk40t/meerk40t/commit/69e8ad88fbb9582233d6a55f98f417a6002f2b2b

Should maybe be due out sometime soon.

**Comment by tatarize** [comment]
Now live.
