### ISSUE TITLE
operation settings window bugged

### ISSUE THREAD

**Issue by panp0d** [meerk40t/meerk40t#481]
cant open engraving options   
![2021-08-09 (2)](https://user-images.githubusercontent.com/82674157/128780461-291514eb-70d6-435f-8647-4d26acee6211.png)

**Comment by tatarize** [comment]
If the window is somehow vanished I'd try tools, reset windows, and try again. I've not tried bugging a window, but sometimes when I run two screens it gets stuck at the other screen or something.

**Comment by panp0d** [comment]
that fixed it thanks

**Comment by tatarize** [comment]
The most likely reason is you did something weird with it and it remembered the setting there and hid under your toolbar or something weird. I'm not sure if there's other ways to break a window.

**Comment by Sophist-UK** [comment]
As a note for the future, it would be good if MK could check that the window is actually positioned on the screen when it is opened and if it is no longer on a screen, do a reset just for that window.
