### ISSUE TITLE
RMB on path/group has no effect if project/parts is selected

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#49]
Might be related to #45 
If Job parts or Project is selected/highlighted, right clicking on "Group" or one of the paths does not bring up pop up menu.
While mouse button is down, "project" or "job parts" selection is gone (no blue highlight anymore), but reverts to selected when mouse button is released.

**Comment by tatarize** [comment]
Yeah, right clicking doesn't switch the selection in the tree. It's likely responsible for both of those bugs.

**Comment by tatarize** [comment]
Fixed in 0.1.9
