### ISSUE TITLE
Mouse Resize and Edge of Objects poorly reacts.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#495]
I've run into this a couple times and take a couple stabs at it, but I never solved it correctly. The corners unsets the mouse cursor instantly causing the edge to seem very small.

**Comment by Sophist-UK** [comment]
I have found one bug which has improved things - going to keep working on it to see if I can improve it further.

**Comment by Sophist-UK** [comment]
Found a second bug - still not much better however.
