### ISSUE TITLE
Impractical size divisions on "dynamic rulers"

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#52]
See screenshot:
![2019-09-27 10_21_16-MeerK40t](https://user-images.githubusercontent.com/46349482/65754182-c7d71a00-e110-11e9-9090-65e8850b45f1.png)

Seems like it would be more logical to have marks at rounded numbers (ie every x mm/cm)

**Comment by tatarize** [comment]
Okay, fixed. And it doesn't interfere with anything so I'll be able to push it to the master branch in short order.

![usable-grid](https://user-images.githubusercontent.com/3302478/65776739-8ede7b80-e0f7-11e9-89fb-e335f756ea62.png)

**Comment by tatarize** [comment]
This is now live in 0.1.5
