### ISSUE TITLE
Transparent PNG imported into SVG gives black background on laser

### ISSUE THREAD

**Issue by diamened** [meerk40t/meerk40t#559]
I've noticed this yesterday. I have this SVG created with Inkscape and it contains an imported PNG image that has a transparent background. When I open it in Meerk40t it correctly classifies it as image and shows ok on screen but when I send it to the laser it engraves a black square where the background should be transparent. 
Running on Linux Mint 20.2. 
Image attached
[Viking Runestone 02.svg.zip](https://github.com/meerk40t/meerk40t/files/7147119/Viking.Runestone.02.svg.zip)

**Comment by diamened** [comment]
I've noticed this issue has already been reported. Sorry

**Comment by tatarize** [comment]
NP. This made me revisit and publish the correction.
