### ISSUE TITLE
[Sticky] Optimisation ideas

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#596]
This issue is raised as a repository for ideas about how to speed up optimisation.

* [x] Do not look for nearest segment after every segment - instead try to burn the next segment on the subpath, only looking at other segments when you need to travel.
* [x] Optimise Inner Path identification so that it only checks groups and not segments
* [x] For Merge Passes, maintain a pass count on the CutObject in order to avoid having independent CutObjects for each pass which then need to be searched through on a travel move
* [x] Fix the inner path identification so that rasters are inside a closed cut if any point is inside (different from vectors).
* [x] Optimise raster image creation so that it creates multiple smaller images where time taken to sweep large empty areas is greater than the time needed for an extra acceleration/deceleration for an extra separate raster.
* [x] Optimise for components by burning the all inside elements of an outside cut before moving only another area.
* [x] Optimise single large rasters elements with a lot of empty space by breaking them into smaller elements before above optimisation. (Needs to be before as otherwise you will merge them all back again. It might be beneficial to break the above raster optimisation by grouping literally overlapping rasters and creating many images, then breaking apart these large images, and then combining close into grouped images where this is better than doing them separately (combining happening after inside identification if grouped inside is selected, and before inside identification if grouped inside is not selected), 
* [ ] In the Candidates routine, if a path segment in a sub-path/CutGroup has fewer burns than the preceding path segment then always give it as a candidate, otherwise only give it as a candidate if the start point is more than a certain distance from the previous candidate. If a sub-path contains many small segments, this will reduce the number of subpaths considered as candidates without substantially reducing the travel optimisation.
* [x] Use numpy for inner first identification, or greedy or 2-opt. If necessary explicitly parallelise numpy usage.
* [x] Extend numpy usage with GPU alternative(s) to numpy.
* [ ] Instead of only using start/end points as a travel point, consider calculating the nearest point of the line joining the start and end points (using SciPy?). Obviously some PathSegment types are easier than others to calculate this. It should be possible to limit the list of paths we do this for as some paths can be shown to be more distant than others based only on their end points.
* [ ] Rather than "greedy" being single minded about the absolute shortest travel move, instead we look at the shortest two (or three) moves and look 2 or three moves ahead to see whether a slightly smarter travel move would be better.

**Comment by Sophist-UK** [comment]
On the initial numbering scheme:

### 1. Stay on path
Implemented

### 2. Simplify large numbers of short PathSegments
> This is unneeded. We use zingl-bresenham curves. We don't subdivide cuts into straight line segments to begin with. We merely draw the curves within our native plot sequence. It's much better to do this way. But, unless the user has divided their curve that way, the curve will be fed into the plotplanner and decomposed into octagonal and diagonal moves, and this will pixel perfect plot the cut. It also makes it scale invariant.

My suggestion for reducing many short PathSegments to a fewer number of Bezier curves was to reduce the time needed to optimise, not for improving cut time. With hindsight I think my brain-dump suggestion to change segments to a simpler type was unnecessary.

However, simplifying large numbers of short PathSegments to significantly fewer PathSegments at load time (optional setting to enable this) might be beneficial at optimise time. And of course these would be preserved if you did a save, so potentially the overhead of reducing PathSegments would only happen on raw svgs.

### 3. Python sort
> 1. The power of the sorting there is somewhat negated this is a NLog(N) process to sort the list and it's an N process to merely look at things. You can't do that faster without storing the proper values in a more useful manner. There's a lot of options for solving K cases of find the closest point to point Q.

I have tried this - and as you suggested it would be, it was actually slower.

### 4. / 5. Numpy etc.
> 2. Numpy isn't really a requirement. This would make it a requirement.
> 3. CuPy isn't a requirement, this would make it a requirement.

I was not intending to suggest that we should make them a requirement - but should take advantage if they are available.

#### 6. Clustering
> Limited the checked points is the method that _all_ solutions to nearest point problems employ. This is usually done by some manners of chunking the points into clusters and determine since no point is nearer to this point than the edge of the cluster the fact that the point is in that cluster proves it cannot be closer so do not check that point cluster. I've coded my own novel algorithm for this which I feel is a lot easier.

SVGs with groups may already have information that can be used for a sort of clustering. We could potentially do some optimisation based on Groups.

But I think you are right - the O() of the algorithm is more important than parallelisation because for large SVGs, O(NLogN) or O(N^2) will quickly overtake whatever parallelism you can achieve on CPU or even GPU.

>    * Sort all candidates into two lists, sorted by x coord and y coord. (Occurs 1 time, O(NlogN)).
>    * Find position of current point in the sorted lists. (log(n), binary search)
>    * Iterate within both list in the +x, +y and -x and -y direction. Storing the current best solution.
>    * Stop search in that direction if and when the current closest point is closer than the distance in _only_ the one coordinate. (Since if dx > d_curr, it doesn't matter what the y-value is all candidates in that direction disqualified since they must be further away).
>    * The algorithm is log(n) for finding a point within the field. So we're doing this for N points or so gives us NLogN, as the overall solution. The current solution is N^2, your proposed resort each time thing is N^2log(N).

Yes. 

If we are doing pure python where all algorithms are possible, then this would seem to be optimal. But using e.g. numpy where numpy has some things it does in C in parallel, but some things that need to come back to single-threaded python for processing, O() still trumps, but it may still be faster to have a slightly less optimal algorithm (which is still O(NlogN)) but which utilises specific numpy features.

**Comment by tatarize** [comment]
> I think that greedy is a form of clustering in the sense that a lot of the time the travel moves are likely to be optimal, 

Clustering in context refers to when you cluster euclidean space to solve greedy faster because you can use clustered algorithms to solve nearest point problems faster than O(N) and lets you solve greedy faster than O(N^2). 

Numpy greedy would be brute force. So rather than O(N*log(n)) we're doing O(N^2) but trying to make up for the difference with the raw speed of the combined operations in the C code. -- The bigger issue is that it's not constrained either. Or would need to be constrained rather than just search the set of all endpoints. You need to search the set of all endpoints which occur from within the inner first candidate list.

http://honors.cs.umd.edu/reports/kuang.pdf

I think we could actually make a 2-opt that works for our HTSP problem. We drop invalid nodes and proceed to perform a cheapest valid insert, probably in a brute force manner. 

https://stemlounge.com/animated-algorithms-for-the-traveling-salesman-problem/

So in theory a correctly done numpy solution could help here.

---

Though at a certain point we're going to have way more trouble with the polygon in polygon algorithm timewise than the optimizations here.

**Comment by Sophist-UK** [comment]
-This is NOT completed - nor will it ever be as there will always be further potential optimisations to consider. 

However, I would like you to confirm that my image / raster optimisation that is in 0.7 has been ported forward to 0.8 (if you cannot determine the margins from the speed, then a fixed margin of (say) 500mil would probably do).

And I am pretty certain that some of the above suggestions have not been implemented yet - like use of numpy for my suggestion of greedy and your suggestion, nor e.g. a new algorithm I have in mind for 2-opt etc.
