### ISSUE TITLE
SVG text should be accounted for.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#61]
Even without actually rendering the text, it would be nice and correct make a text object for svg text.

**Comment by tatarize** [comment]
https://catherineh.github.io/programming/2018/02/01/text-to-svg-paths

I use a different earlier fork of the methods behind svgpathtools, given that this isn't too hard to do.  And will provide internal ability to do this glyph editing on the fly. So you could have text paths that are editable inside the program or flow a series of them etc.

**Comment by tatarize** [comment]
https://github.com/rougier/freetype-py

Seems perfect for this task.

**Comment by tatarize** [comment]
Added the Parsing and the Element. I did not add the actual conversion to paths or the execution of those paths. And it says much more obviously that this is NOT IMPLEMENTED in that you had text in your SVG and that text got eaten because I don't deal with it yet.

**Comment by tatarize** [comment]
Briefly added an attempt to parse the text with freetype-py but gave it up when it became a bit of a time suck. Also, not sure how to access system fonts directly and it might be reasonable to use access from https://fonts.google.com/ as then it would basically have all the fonts you needed and could locate most of the families even gave it a font from a different system that wasn't supported in the system set to run the font.

**Comment by tatarize** [comment]
Though for now, permit cheating. Allow text to path functionality, if the user provides a path the inkscape.

Better working functionality is great, but no sense letting the perfect prevent the good.

**Comment by tatarize** [comment]
You can actually make text and directly raster the objects.

**Comment by jpirnay** [comment]
Obsolete
