### ISSUE TITLE
Right Click Menu, shows file/group options.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#615]
Originally raised in #599 

> I think that these are issues of selection. When you open an image you get a File Node as well as an Image node (which IMO is correct - without the File node you cannot reload the image) and the File Node is what is selected so you get the Group element right click choices.
> 
> There is also an issue of selection in the scene being reflected correctly in the tree. For example, click on the outside of the elements in the scene and the tree selections are not cleared. If I load the Heather image, Control click in tree to clear selection(s), then click the image in the scene, I get both file node and image node shown in grey (emphasised?), but image opnode is not highlighted, right-click in scene doesn't include Remove and right-click in tree turns both element nodes blue (selected?) but still doesn't show remove. If I clear the selections with Control-click in tree and then reselect both of them in the same way, then I do get Remove in the right click menu.
> 
> There are lots of such inconsistencies. In short, I think we need to make the right-click menus reflect:
> 
> The node/node type that is right clicked.
> The nodes / node types that are selected.
> The nodes / node types that are emphasised.

**Comment by Sophist-UK** [comment]
Fixed.
