### ISSUE TITLE
Add logging option

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#62]
Just a suggestion that _might_ help you troubleshooting in the future.
Add a command line option that enables writing the log to a file instead of stdio.
Option in the settings would be an option as well, but that only works if the software starts up correctly (so wouldn't help if the issue is during startup).

**Comment by tatarize** [comment]
This is now fixed in #64 and is live in version 0.1.6 now. Though I did forget a couple carriage returns.
