### ISSUE TITLE
[Bug?] Execute/StepRepeat includes Homes, Beeps etc. between

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#657]
IMO (and I may be wrong) automatic before/after special operations (like home, beep etc.) should apply to the job as a whole and not to each step in a `Step Repeat`.

**Comment by Sophist-UK** [comment]
P.S. As a consequence, it does the second one in exactly the same place as the first.

**Comment by tatarize** [comment]
I'm not sure how to to do this without a more advanced editor for raster subpaths, which isn't a terrible idea. If you homed it shouldn't matter since step repeat changes the offset. Though that might actually just be changed in expected position.
