### ISSUE TITLE
Turn on "reduce travel time" and "cut inner first" by default?

### ISSUE THREAD

**Issue by jaredly** [meerk40t/meerk40t#753]
Are there important reasons that they're currently off-by-default? I feel like they're what most users expect / want.

reduce travel time turned off (the current default)
![image](https://user-images.githubusercontent.com/112170/150379195-44b26517-8c3f-4911-a639-b5ae27eab50f.png)

tuned on, 🏎🏎🏎🏎
![image](https://user-images.githubusercontent.com/112170/150379222-63969e34-19d7-42ea-b1a9-73d5fb6a7698.png)

**Comment by tatarize** [comment]
Was previously much slower. I think that was most of the reason. Sometimes you could look down on like a couple minutes.

**Comment by jaredly** [comment]
thanks!

**Comment by Sophist-UK** [comment]
Welcome to the Meerk40t Contributors Hall of Fame!!!!!!
