### ISSUE TITLE
Add a note to Interrupts?

### ISSUE THREAD

**Issue by jaredly** [meerk40t/meerk40t#764]
I'd love to be able to add a note next to interrupts. I'm using them to adjust the power settings, and it'd be great to have listed the power that I want to set it to.

**Comment by tatarize** [comment]
I'd think there'd be pretty limited use there but it wouldn't be too hard to do. Not sure how to interface it either. I guess just interrupt with some arguments and catch it for the cli and gui interrupt code there.

**Comment by Sophist-UK** [comment]
As I commented on [Discord](https://discord.com/channels/910979180970278922/910983847435448420/934368134322847764):

You would IMO be better off adjusting your Operation speeds (and for rasters, steps - and if absolutely necessary PPI) so that all operations are burned with the same hardware power settings (ideally full power i.e. 12mA).

**Comment by tatarize** [comment]
Yeah, but that doesn't detract from the note, there might be other messages that you'd like to send with interrupts and they totally can provide messages. If somebody made a meerk40t file that was pre-set you could very well use interrupt-messages to make sure your instructions are followed. "At this point turn the wood over, the rest of these cuts are for the back side." Like that's be some weird things but should be completely possible to do with a little tweaking.

**Comment by Sophist-UK** [comment]
True - and it would certainly make more sense when we are able to save and restore special operation in an svg file.

**Comment by tatarize** [comment]
And the discussion in discord seems to have gone in a very useful direction, namely just make a different node type that runs a line of console command and can be edited. Then modify the commands to allow an interrupt command. In theory, you could just interject console commands at different points in the spooling process. Assuming the commands are generally rather global this would be a pretty versatile solution. Admittedly a couple commands in the cmdop nodes don't have clear console command parallels but that could be rectified. You could maybe change the display label of the node type depending on the command a little bit to hardcode a sort of look and feel in there.
