### ISSUE TITLE
[Bug]: Tree Selection/Delete Key issues

### ISSUE THREAD

**Issue by tiger12506** [meerk40t/meerk40t#803]
### Summary Description

This is for tracking any remaining tree selection/delete key issues remaining before next release. Probably any fixes should be applied to main branch, and merged also into tatarize-services.

### MeerK40t Version

main

### MeerK40t Type

Git

### Your Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sophist-UK** [comment]
#793 was the PR that was supposed to fix the delete key issues.

Have there been any examples of it not working as expected after this was merged. If so please document them here as @tiger12506 suggests.

**Comment by tatarize** [comment]
I cannot delete text objects.

**Comment by Sophist-UK** [comment]
I can't see anything directly in #793 code that would cause this. My first thought was it was checking for Shape and SVGImage and I had omitted to list SVGText but it turns out that it deletes everything.

I just tested it on SVGText nodes (both in Ops and Elems) and it works just fine for me.

**Comment by Sophist-UK** [comment]
Closing as the SVGText issue cannot be replicated and there have been no reported issues since this was released in a full release.
