### ISSUE TITLE
[Suggestion]: Console/CLI colors.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#814]
### Summary Description

Use RichText in gui Console to convert ANSI color coding. This would also permit ansi text colors in console. The console would convert the ANSI color coding to actual colors and bold. And they would be generally displayed in CLI mode.

### Current functionality

Currently all text is unformatted plain text.

### Future functionality

Color that attacks the eyes like angry fruit salad that hates you.

### MeerK40t Version

0.7.4010

### MeerK40t Type

Git

### Your Operating System

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Sophist-UK** [comment]
Functionality delivered in #849 with minor fixes in #855.
