### ISSUE TITLE
[Enhancements] Simulation ideas

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#848]
1. Show separate steps for separate images (currently combined into a single animation step)
2. Combine with Execute into a single "Burn" tab - rename "Tools" tab "Design", rename "Home" tab "Layout".
3. Show paths and travel move's as separate animations
4. Do animation based on steps but time between steps based on burn time. (Images / Rasters to be animated using variable clip window and 10x faster than real-time).
5.

**Comment by tatarize** [comment]
This was, oddly enough, finished up late last year.
