### ISSUE TITLE
[Bug?] wxmscene registers a console. Is this correct?

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#850]
https://github.com/meerk40t/meerk40t/blob/3dd762b0a33d5889487ce00748b4c71b698d103d/meerk40t/gui/wxmscene.py#L36 has the same registration as  https://github.com/meerk40t/meerk40t/blob/3dd762b0a33d5889487ce00748b4c71b698d103d/meerk40t/gui/panes/consolepanel.py#L27 . Is this correct or a bug?

**Comment by tatarize** [comment]
Bug. It should likely be pane/scene. It doesn't matter as much since the latter code likely hits later and you usually can't disable the scene anyway.

**Comment by Sophist-UK** [comment]
I tried changing it to pane/scene and MK crashed on load with some sort of wxwidget assert. Gonna have to leave this one to you to sort.

**Comment by tatarize** [comment]
```python
def register_panel_scene(window, context):
    # self.notebook = wx.aui.AuiNotebook(self, -1, size=(200, 150))
    # self._mgr.AddPane(self.notebook, aui.AuiPaneInfo().CenterPane().Name("scene"))
    # self.notebook.AddPage(self.scene, "scene")

    panel = MeerK40tScenePanel(window, wx.ID_ANY, context=context)
    pane = aui.AuiPaneInfo().CenterPane().Name("scene").Caption("Scene")
    pane.dock_proportion = 600
    pane.control = panel

    window.on_pane_add(pane)
    context.register("pane/scene", pane)
```

The problem is the code elsewhere uses the set Caption, which doesn't exist for pane to make a menubar value.

Corrected like that and you can toggle the scene on and off, which is a little weird.

**Comment by Sophist-UK** [comment]
I fixed this a different way - by not adding to a menu anything without a caption.
