### ISSUE TITLE
rPi and general issues list (Tat's brother / @joerlane)

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#879]
This list is copied from Discord and sequenced by whether it should be fixed in 0.7.6 or 0.8 or TBD. (Very easy fixes in 0.7.6, harder ones in 0.8 because of the difficulties in rolling such changes made in 0.7.6 int 0.8, TBD if fix complexity is unknown.)

These were tested on rPi executable - we need to check whether they are rPi specific or also occur on other O/ses.

### TBD
* [ ] Call Blob something more meaningful
* [x] wxWait calls display a black box which says nothing? (O/s? rPi?)
* [ ] rPi is missing tree open/close arrows - @joerlane says this is a Linux issue and depends on windows manager. Probably not fixable.
* [x] When last CutObject clears and background reverts from red to grey cannot use emergency stop.
* [ ] Raster with big white area caused a stall/stutter - unclear whether this is during raster image generation or during burn (in a burn it would be counterintuitive since instruction stream should be short)
* [ ] View invert - doesn't work on rPi - should we drop it altogether?
* [x] "Remove" should be for Ops branches, "Delete" for Element branches
* [x] "Append operation"->"Add operation" (Use on Operations top node should pre-pend not append,)
* [x] rPi simulation of cut was incorrectly zoomed
* [x] Manually classified element without stroke to cut operation did not show in simulation - what should we do with elements with no stroke in vector ops?
* [ ] Rasters appear grey in simulation but vectors show as colours - this is inconsistent. Should everything be grey scale and based on burn PPI i.e. use grey scale to show vector PPI

 (removed completed)

Please feel free to edit this list and move items to where you think they should be put.

**Comment by tatarize** [comment]
Completed or addressed as will not complete.
