### ISSUE TITLE
[Bug] Touchscreen move does move in scene but does not actually move objects

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#990]
Touchscreen move does move in scene but does not actually move objects

V0.7.6

![image](https://user-images.githubusercontent.com/3001893/163561528-53732ebe-c451-4afb-8913-5ade1feba68e.png)

**Comment by tatarize** [comment]
Hm. Odd. I'll add it to the itinerary to check. My brother has a touch screen.
